{{- if eq .Values.cs.useCSDfcConfigMap false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rqm-dfcproperties-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace}}
data:
  dfc.properties: |
   {{- range .Values.dfc.properties }}
   {{ . }}
   {{- end }}
{{ end }}