{{- if .Values.global.dctmclientinstaller.enabled }}
#Service
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType | default .Values.global.webappServiceType }}
  ports:
    - port: {{ template "adminconsole.servicePort" .  }}
  selector:
    app: {{ .Chart.Name }}
---
#StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Chart.Name }}
   namespace: {{ .Values.namespace | default .Release.Namespace  }}
spec:
  serviceName: "{{ .Chart.Name }}"
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/customcert: {{ include (print $.Template.BasePath "/adminconsole-custom-certificate.yaml") . | sha256sum }}
        checksum/catalinaconfig: {{ include (print $.Template.BasePath "/adminconsole-catalina-configmap.yaml") . | sha256sum }}
        checksum/dfc: {{ include (print $.Template.BasePath "/adminconsole-dfc-properties.yaml") . | sha256sum }}
        checksum/resiapiruntime: {{ include (print $.Template.BasePath "/adminconsole-rest-api-runtime-properties.yaml") . | sha256sum }}
        checksum/serverxml: {{ include (print $.Template.BasePath "/adminconsole-server-xml.yaml") . | sha256sum }}
        checksum/settings: {{ include (print $.Template.BasePath "/adminconsole-settings-properties.yaml") . | sha256sum }}
    spec: 
      securityContext:
        fsGroup: {{ .Values.fsGroup | default .Values.global.fsGroup }}  
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: {{ .Values.runAsNonRoot }}
        runAsUser: {{ .Values.runAsUser }}        
{{ if (empty (.Values.images.pullSecrets | quote) | ternary .Values.global.pullSecretName .Values.images.pullSecrets) }}
      imagePullSecrets:
      - name: {{ .Values.images.pullSecrets | default .Values.global.pullSecretName }}
{{ end }}
      {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 6 }}
      {{- end }}
      initContainers:
      - name: adminconsoleextension
        image: {{ .Values.extensionImage.repository | default .Values.global.repository }}/{{ .Values.extensionImage.name }}:{{ .Values.extensionImage.tag }}
        imagePullPolicy: {{ .Values.extensionImage.pullPolicy | default .Values.global.pullPolicyType }}
        command: ['/bin/sh', '-c', '. /opt/adminconsole/initstartup.sh']
        volumeMounts:
          - name: extensionpvc
            mountPath: /opt/d2extension
            subPath: adminconsole
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
{{- if .Values.extraInitContainers }}
{{ include "resolveInitContainers" (dict "initContainerLists" .Values.extraInitContainers "global" .Values.global "nindent" 6) }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountName | default .Values.global.documentumserviceaccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.repository | default .Values.global.repository }}/{{ .Values.images.name | default .Values.global.appserverImageName }}:{{ .Values.images.tag | default .Values.global.appserverImageTag }}
        imagePullPolicy: {{ .Values.images.pullPolicy | default .Values.global.pullPolicyType }}
{{- if .Values.customConfigurations.custom }}
        command: ['bin/sh', '-c', 'mkdir -p /opt/AdminConsole-install;sudo cp -pRf /opt/d2extension/adminconsole/* /opt/AdminConsole-install/;sudo chown -Rf 1000:1000 /opt/AdminConsole-install/;. /opt/AdminConsole-install/extensionstartup.sh']
{{- else }}
        command: ['bin/sh', '-c', 'mkdir -p /opt/AdminConsole-install;cp -pRf /opt/d2extension/adminconsole/* /opt/AdminConsole-install/;sudo chown -Rf 1000:1000 /opt/AdminConsole-install/;. /opt/AdminConsole-install/extensionstartup.sh']
{{- end }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}       
        env:
        - name: KUBERNETES
          value: "true"
        - name: CONTAINER_NAME
          value: {{ .Chart.Name | quote }}
        - name: D2INSTALL_USE_CS_CUSTOM_SCRIPTS_APPROACH
          value: "true"        
        - name: DOCBROKERS_COUNT
          value: {{ .Values.docbroker.count | quote }}
        - name: DOCBROKER_SERVICE_NAME
          value: {{ .Values.userName }}{{ .Values.docbroker.serviceName | default .Values.global.dbrServiceName }}
        - name: DOCBROKER_CLUSTER_SPACE
          value: {{ .Values.env.domain | default (include "documentum.envDomain" .) }}
        - name: DOCBROKER_PORT
          value: {{ .Values.docbroker.port | default .Values.global.dbr_port | quote }}                     
        - name: METHOD_SVR_HOST
          value: {{ .Values.methodsvr.containerName }}-jms-service
        - name: METHOD_SVR_PORT
          value: {{ .Values.global.jmsPort | quote }}
        - name: GLOBAL_REGISTRY_DOCBASE_NAME
          value: {{ .Values.docbase.name | default .Values.global.docbase }}
        - name: BOF_REGISTRY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: globalRegistryPassword          
        - name: INSTALL_OWNER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: installOwner        
        - name: INSTALL_OWNER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: installOwnerPassword
        - name: INGRESS_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: ingress.keystorepassword
        - name: DOCBASE_NAME
          value: {{ .Values.docbase.name | default .Values.global.docbase }}         
        - name: ENABLE_OTDS
          value: {{ (empty (.Values.restApiRuntime.OTDS.enable | quote) | ternary .Values.global.otdsEnabled .Values.restApiRuntime.OTDS.enable) | quote }}

        - name: OTDS_AUTH_SVC
          value: {{ .Values.restApiRuntime.OTDS.authSvc | default .Values.global.otdsAuthSvc | quote }}        
        - name: OTDS_CLIENT_ID
          value: {{ .Values.restApiRuntime.OTDS.clientId | default .Values.global.oauthClient | quote }}
        - name: TOMCAT_JVM_ARGS
          value: {{ .Values.env.tomcatJVMArgs }} 
        - name: WEBAPP_NAME
          value: {{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}
        - name: TOMCAT_LOG_FILE_ROTATION
          value: {{ .Values.tomcat.logfilerotation | quote }}
        - name: TOMCAT_LOG_FILE_SIZE
          value: {{ .Values.tomcat.logfilesize | quote }}
        - name: TOMCAT_LOGROTATE_FREQUENCY
          value: {{ .Values.tomcat.logrotateFrequency | quote }}
        - name: REMOVE_DOCU
          value: {{ .Values.removeDocumentation | default .Values.global.removeDocumentation | quote }}   
        - name: DMS_SERVICE_NAME
          value: {{ .Values.dms.dmsServiceName | default .Values.global.dmsServiceName }}          
        - name: DMS_HTTP_PORT
          value: {{ .Values.dms.dmsHttpPort | default .Values.global.dmsHttpPort | quote}}   
        - name: DSIS_STATUS_CHECK_RETRY_COUNT
          value: "{{ .Values.vault.statusCheckRetryCount  }}"
        - name: DSIS_STATUS_CHECK_TIME_INTERVAL
          value: "{{ .Values.vault.statusCheckTimeInterval  }}"          
{{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate ) }}
        - name: DOCBASE_USE_CERTIFICATES
          value: {{ (empty (.Values.certificate.use_certificate | quote ) | ternary .Values.global.useCertificate .Values.certificate.use_certificate ) | quote }}
{{ end }}
      {{- if (empty (.Values.newrelic.enable | quote) | ternary .Values.global.newrelic .Values.newrelic.enable) }}
        - name: NEWRELIC_ENABLE
          value: {{ (empty (.Values.newrelic.enable | quote) | ternary .Values.global.newrelic  .Values.newrelic.enable) | quote }}            
        - name: NEWRELIC_APP_NAME
          value: {{ .Values.newrelic.app_name }}.{{ .Release.Namespace }}
        - name: NEWRELIC_PROXY_HOST
          value: {{ .Values.newrelic.proxy_host | default .Values.global.newrelicProxyHost }}
        - name: NEWRELIC_PROXY_PORT
          value: {{ .Values.newrelic.proxy_port | default .Values.global.newrelicProxyPort | quote  }}
        - name: NEWRELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: newrelicLicensekey
      {{- end }}    
{{- if .Values.customConfigurations.custom }}
        - name: CUSTOM_IMPORT
          value: {{ .Values.customConfigurations.custom | quote }}
        - name: LOCALE_NAME
          value: {{ .Values.customConfigurations.locale | quote }}
{{- end }}
{{- if (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) }} 
        - name: DFC_DSIS_ENABLED
          value: {{ (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) | quote }}
        - name: DFC_DSIS_DAEMON_TOKEN
          value: {{ .Values.vault.daemontoken | quote }}
        - name: DFC_DSIS_DAEMON_URL
          value: {{ .Values.vault.daemonurl | default "http://localhost:8200/dsis" | quote }}          
{{- end }}   
{{- if .Values.MIPTrusted.enable }} 
        - name: MIP_ENABLED
          value: {{ .Values.MIPTrusted.enable | quote }}
{{- end }}      
      {{- if .Values.customcert.enable }}
        - name: CUSTOM_CERTIFICATE
          value: {{ .Values.customcert.certName | quote }}
      {{ end }}      
        - name: DFC_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: csCertTrustPassword
    {{- if eq .Values.catalina_configurations.enable true  }}
        - name: CATALINA_OPTS
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-catalina-configmap
              key: catalina_opts
    {{- end }}
    
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 8 }}
{{- end }}             
        ports:
        - containerPort: 8080
          name: clientport
        volumeMounts:
{{- if (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) }}
        - mountPath: /opt/dctm_docker/vault_config_map
          name: vault-volume
{{- end }}                                                           
{{- if (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) }}
        - mountPath: /opt/dctm_docker/dsis_binary_volume
          name: dsis-binary-volume
          subPath: dsis-binary
{{- end }}                  
{{- if .Values.customcert.enable }}
    {{ $chartName := .Chart.Name }}
    {{ range $path, $_ :=  .Files.Glob "certificates/*" }}
        - mountPath: /opt/custom/certificates/{{ base $path }}
          name: {{ $chartName }}-custom-certs
          subPath: {{ base $path }}
    {{ end }}
{{- end }}        
        - mountPath: {{ .Values.tomcat.catalinaHome }}/CustomConf/DFCKeystore
          name: {{ .Chart.Name }}-vct
          subPath: {{ .Chart.Name }}_dfc_keystore_file                    
{{- if .Values.cs.custom.scriptinPVC }}
        - mountPath: /opt/D2CS-install
          name: {{ .Values.cs.custom.volumeMountName }}
          subPath: {{ .Values.cs.custom.PVCSubPath }}/d2
{{- else }}            
        - mountPath: /opt/D2CS-install
          name: dcs-data-pvc
          subPath: D2CS-install/d2-dcs 
{{- end }}
{{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
        - mountPath: /opt/dctm/certificate
          name: {{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
          subPath: certificate/{{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
{{ end }}
        - mountPath: {{ .Values.tomcat.catalinaHome }}/CustomConf
          name: {{ .Chart.Name }}-conf-files
        - mountPath: {{ .Values.tomcat.catalinaHome }}/conf/server_configmap.xml
          name: {{ .Chart.Name }}-appserver-server-xml
          subPath: server.xml
        - mountPath: {{ .Values.tomcat.catalinaHome }}/webapps/{{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}/ui/sw-config.json
          name: {{ .Chart.Name }}-sw-config-json
          subPath: sw-config.json
{{- if .Values.customConfigurations.custom }}
        - mountPath: /opt/AdminConsole-install/custom
          name: customconfig
{{- end }}
        - mountPath: /opt/d2extension/
          name: extensionpvc
          subPath: adminconsole
{{ if (empty (.Values.graylog.enable | quote) | ternary (not .Values.global.grayLogEnable) .Values.graylog.enable) }}
        - mountPath: {{ .Values.tomcat.catalinaHome }}/logs/{{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}
          name: shared-logs
          subPath: {{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}/logs
        - mountPath: {{ .Values.tomcat.catalinaHome }}/logs/
          name: shared-logs
          subPath: logs
{{- end }}
{{ $kubeversion := printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor | replace "+" "" | float64 }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if eq .Values.readinessProbe.enable true }}
        readinessProbe:
          httpGet:
            path: /{{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}/services
            port: 8080
{{- if ge $kubeversion 1.19 }}
          initialDelaySeconds: {{ default 60 .Values.readinessProbe.initialDelaySeconds }}
{{- else }}
          initialDelaySeconds: {{ default 300 .Values.readinessProbe.initialDelaySeconds }}
{{- end }}
          periodSeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 60
{{- end }}
{{- if eq .Values.livenessProbe.enable true }}
        livenessProbe:
          httpGet:
            path: /{{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}/liveness
            port: 8080
{{- if ge $kubeversion 1.19 }}
          initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds }}
{{- else }}
          initialDelaySeconds: {{ default 300 .Values.livenessProbe.initialDelaySeconds }}
{{- end }}
          periodSeconds: 60
          failureThreshold: 5
{{- end }}
{{ if ge $kubeversion 1.19 }} 
{{- if eq .Values.startupProbe.enable true }} 
        startupProbe:
          httpGet:
            path: /{{ .Values.env.webappName | default .Values.global.adminConsoleWebappName }}/services
            port: 8080
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 60
          periodSeconds: 60  
 {{- end }}
 {{- end }}            
      volumes:
{{- if (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) }}
        - name: vault-volume
          configMap:
            name: {{ .Values.vault.vault_configmap }}
{{- end }}     
{{- if (empty (.Values.vault.enable | quote) | ternary .Values.global.isVaultEnabled .Values.vault.enable) }}
        - name: dsis-binary-volume
          persistentVolumeClaim:
            claimName: dsis-binary-pvc
{{- end }}                                                                                            
{{ if (empty (.Values.graylog.enable | quote) | ternary (not .Values.global.grayLogEnable) .Values.graylog.enable) }}
        - name: shared-logs
          emptyDir: {}
{{ end }}
{{- if .Values.customConfigurations.custom }}
        - name: customconfig
          emptyDir: {}
{{- end }}
        - name: extensionpvc
          persistentVolumeClaim:
            claimName: {{ .Values.extension.pvcName | default .Values.global.tomcatbase_commonpvcname }} 

        - name: {{ .Values.cs.custom.volumeMountName }}
          persistentVolumeClaim:
            claimName: {{ .Values.cs.custom.scriptPVCname }}
{{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
        - name: {{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
          persistentVolumeClaim:
            claimName: {{ .Values.certificate.dbrserviceName | default .Values.global.dbrServiceName }}-pvc
{{- end }}
{{- if .Values.customcert.enable }}
        - name: {{ .Chart.Name }}-custom-certs
          secret:
            secretName: {{ .Chart.Name }}-custom-certs
{{- end }}
        - name: {{ .Chart.Name }}-sw-config-json
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-sw-config-json
        - name: {{ .Chart.Name }}-conf-files
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-dfc-properties      
            - configMap:
                name: {{ .Chart.Name }}-log4j2-properties    
            - configMap:
                name: {{ .Chart.Name }}-rest-api-runtime-properties  
            - configMap:
                name: {{ .Chart.Name }}-settings-properties          
            - configMap:
                name: {{ .Chart.Name }}-mailapp-properties
            - configMap:
                name: {{ .Chart.Name }}-trust-properties
        - name: {{ .Chart.Name }}-appserver-server-xml
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-server-xml
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-vct
    spec:
      accessModes:
        - {{ .Values.persistentVolume.vctAccessModes }}
      resources:
         requests:
            storage: {{ .Values.persistentVolume.size }}
      storageClassName: {{ .Values.persistentVolume.storageClass | default .Values.global.rwoStorage }}
{{ if (empty (.Values.graylog.enable | quote) | ternary (not .Values.global.grayLogEnable) .Values.graylog.enable) }}
  - metadata:
      name: shared-logs
    spec:
      accessModes:
        - {{ .Values.graylog.volumeClaimTemplate.logVctAccessModes }}
      resources:
         requests:
            storage: {{ .Values.graylog.volumeClaimTemplate.logVctSize }}
      storageClassName: {{ .Values.graylog.volumeClaimTemplate.logVctStorageClass | default .Values.global.rwoStorage }}
{{ end }}
{{- end }}