apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.headless.annotations }}
  annotations:
{{ .Values.headless.annotations | toYaml | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
{{- range $key, $port := .Values.ports }}
    - name: {{ $key }}
      port: {{ $port.containerPort }}
      targetPort: {{ $key }}
      protocol: {{ $port.protocol }}
{{- end }}
  selector:
    app: {{ .Values.service.name }}
    release: {{ .Release.Name }}
