{{- if eq (default .Values.global.newrelic .Values.newrelic.enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-configmap-ext
data:
  {{ .Values.newrelic.configurationFile }}: |-
{{ .Files.Get .Values.newrelic.configurationFile  | indent 4 }}
{{- end }}