{{- if (default false .Values.serviceAccount.createServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Values.global.documentumserviceaccount .Values.serviceAccount.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
