apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{- include "dctm-rest.custom-labels" . | indent 4 }}
{{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ default .Values.global.webappServiceType .Values.serviceType }}
  ports:
    - port: {{ template "dctm-rest.servicePort" .  }}
  selector:
    {{- include "dctm-rest.custom-labels" .  | indent 4 }}