# Default values for d2config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  hostShortName: 
  hostDomainName: 
  class: nginx
  annotations:
    # nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    
  #When GCP native load balancer is used, the pathType should be updated to Prefix, otherwise it should be default value which is ImplementationSpecific
  pathType: ImplementationSpecific
  
# List of valid values are CFCR, Azure, AWS, GCP
cloudPlatform: CFCR

tls:
  enable: false
  secretName:

d2configservice:
    enable: 
    serviceName: d2config
    path:   

adminConsoleService:
  enable: 
  serviceName: adminconsole
  path: 
    
workflowDesignerService:
    enable: 
    serviceName: dctm-workflow-designer-service
    servicePort: 8080
    path: DocumentumWorkflowDesigner
    
daService:
  enable: 
  serviceName: da-svc
  servicePort: 8080
  path: da

dfsService:
  enable: 
  serviceName: dfs-server
  servicePort: 8080
  path: dfs
  
cmisService:
  enable: 
  serviceName: dctm-cmis
  servicePort: 8080
  path: dctm-cmis

xdaService:
  enable: 
  serviceName: xda
  servicePort: 7000
  path: xda
  
documentumSearchService:
  enable: 
  serviceName: ds-admin
  servicePort: 8800
  path: admin

dcc:
  enable: 
  prefix:  
  consul:
    prefix: consul
    service:
      servicePort: 8500  
    uipath: ui
    backendpath: v1   
  syncagent:
    enabled: 
    prefix: syncagent
    path: syncagent
    service:
      servicePort: 8080   

lssftpService:
  enable: 
  serviceName: sftp-svc
  path: sftp-users-management

recordsService:
  enable: 
  serviceName: records-svc
  servicePort: 8080

dmsService:
  enable: 
  serviceName: dctm-dms
  servicePort: 8489
  path: dms-ws

otdsws:
  enable: 
  path: otdsws  
  serviceName: otdsws
  servicePort: 80

assapservice:
  enable: 
  serviceName: assap-svc
  servicePort: 8080
  path: assap

cssapservice:
  enable: 
  serviceName: cssap-svc
  servicePort: 8080
  path: HvpWorker/hvpCommand

assapilmservice:
  enable: 
  serviceName: assap-ilm-svc
  servicePort: 8080
  path: dmwebdav

#extraPaths is used to define additional ingress resources in d2webappscustominstaller section in d2/values.yaml
#extraPaths:
#      - backend:
#          serviceName: {{ .Values.d2webappName }}
#          servicePort: 8080        
#        path: /CustomApp1


