{{- if .Values.global.dctmclientinstaller.enabled }}
{{- if .Values.extension.createPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.extension.pvcName | default .Values.global.tomcatbase_commonpvcname}}
spec:
  accessModes:
    - {{ .Values.extension.PVCAccessMode }}
  storageClassName: {{ .Values.extension.PVCStorageClass | default .Values.global.rwmStorage }}
  {{- if .Values.extension.staticPVName }}
  volumeName: {{ .Values.extension.staticPVName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.extension.PVCSize }}
{{- end }}
{{- end }}
