apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}-secret
type: Opaque
data:
####  tomcatPassword: {{ default "" .Values.tomcat.password | b64enc | quote }}	
  superUserPassword: {{ default "" .Values.docbaseConnection.superUserPassword | b64enc | quote }}
  wfdpassword: {{ .Values.workflowDesignercli.password | b64enc }}
{{- if .Values.global.internalTlsEnable }}
  wfdingressPassword: {{ .Values.trustStore.ingressPassword | b64enc }}
{{- end }}  
{{- if .Values.trustStore.enable }}
  trustStoreFile: |-
    {{ $trustStoreFile := printf "secrets/%s" .Values.trustStore.fileName }}
    {{ .Files.Get $trustStoreFile | b64enc }}
{{- end }}  
