apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-service
{{- with .Values.serviceAnnotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    app: {{ .Values.prefix }}

spec:
  type: {{ .Values.serviceType | default .Values.global.webappServiceType }}
  ports:
  - port: {{ eq .Values.global.internalTlsEnable true | ternary .Values.tomcat.httpsPort .Values.tomcat.httpPort }}
    targetPort: {{ eq .Values.global.internalTlsEnable true | ternary .Values.tomcat.httpsPort .Values.tomcat.httpPort }} 
    name: webdesignerport
  selector:
    app: {{ .Values.prefix }}  
    

