apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-dctm-workflow-designer-log-config
  labels:
    name: {{ .Values.prefix }}-dctm-workflow-designer-log-config
data:
  log4j2: |-
    ###################################################################################
    ############################   Log4j2 internals   #################################
    ###################################################################################
    #The level of internal Log4j events that should be logged to the console.
    # Valid values for this attribute are "trace", "debug", "info", "warn",
    # "error" and "fatal"
    status = info
    #Either "err" for stderr, "out" for stdout, a file path, or a URL.
    dest = err
    #The name of the configuration.
    name = WFDLogs
       
    ###################################################################################
    ############################   Global Properties   ################################
    ###################################################################################
    property.FILENAME = /opt/tomcat/logs/WFDesigner
    property.MIGRATION_FILENAME = /opt/tomcat/logs/WFMigration
    property.IMPORT_FILENAME = /opt/tomcat/logs/WFImport
    
    ###################################################################################
    ############################   Loggers   ##########################################
    ###################################################################################
    
    #RootLogger
    monitorInterval = 30
    rootLogger.level = INFO
    rootLogger.appenderRefs = stdout, designerlogs, migrationlogs, importlogs
    rootLogger.appenderRef.rolling.ref = fileAppender
    rootLogger.appenderRef.stdout.ref = STDOUT
    monitorInterval = 5
    
    ###################################################################################
    ############################    Appender settings   ###############################
    ###################################################################################
    
    #stdout Appender
    appender.stdout.type = Console
    appender.stdout.name = STDOUT
    appender.stdout.layout.type = PatternLayout
    appender.stdout.layout.pattern =  %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %5p [T%t] [%c:%L] %m%n
    appender.stdout.filter.threshold.type = ThresholdFilter
    appender.stdout.filter.threshold.level = TRACE
    
    #WFDesigner Logs File Appender
    appender.designerlogs.type = RollingFile
    appender.designerlogs.name = fileAppender
    appender.designerlogs.fileName = ${FILENAME}.log
    appender.designerlogs.filePattern = ${FILENAME}-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
    appender.designerlogs.layout.type = PatternLayout
    appender.designerlogs.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %5p [T%t] [%c:%L] %m%n
    appender.designerlogs.policies.type = Policies
    appender.designerlogs.policies.size.type = SizeBasedTriggeringPolicy
    appender.designerlogs.policies.size.size=2MB
    appender.designerlogs.strategy.type = DefaultRolloverStrategy
    appender.designerlogs.strategy.max = 100
    
    #WFMigration Logs File Appender
    appender.migrationlogs.type = RollingFile
    appender.migrationlogs.name = migrationAppender
    appender.migrationlogs.fileName = ${MIGRATION_FILENAME}.log
    appender.migrationlogs.filePattern = ${MIGRATION_FILENAME}-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
    appender.migrationlogs.layout.type = PatternLayout
    appender.migrationlogs.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %5p [T%t] [%c:%L] %m%n
    appender.migrationlogs.policies.type = Policies
    appender.migrationlogs.policies.size.type = SizeBasedTriggeringPolicy
    appender.migrationlogs.policies.size.size=2MB
    appender.migrationlogs.strategy.type = DefaultRolloverStrategy
    appender.migrationlogs.strategy.max = 100
    
    #WFImport Logs File Appender
    appender.importlogs.type = RollingFile
    appender.importlogs.name = importAppender
    appender.importlogs.fileName = ${IMPORT_FILENAME}.log
    appender.importlogs.filePattern = ${IMPORT_FILENAME}-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
    appender.importlogs.layout.type = PatternLayout
    appender.importlogs.layout.pattern = %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %5p [T%t] [%c:%L] %m%n
    appender.importlogs.policies.type = Policies
    appender.importlogs.policies.size.type = SizeBasedTriggeringPolicy
    appender.importlogs.policies.size.size=2MB
    appender.importlogs.strategy.type = DefaultRolloverStrategy
    appender.importlogs.strategy.max = 100
    
    ################################################################################
    ############################   WFDesigner Log settings   #######################
    ################################################################################
    
    logger.file.name=com.documentum.xcp.designer
    logger.file.level = INFO
    logger.file.additivity = false
    logger.file.appenderRef.rolling.ref = fileAppender
    
    ################################################################################
    #########################  WFMigration log settings ############################
    ################################################################################
    
    logger.migrationframework.name = com.documentum.xcp.designer.artifacts.project.migration
    logger.migrationframework.level = INFO
    logger.migrationframework.additivity = false
    logger.migrationframework.appenderRef.rolling.ref = migrationAppender
    
    ################################################################################
    #########################  WFImport log settings ############################
    ################################################################################
    
    logger.importframework.name = com.documentum.xcp.designer
    logger.importframework.level = INFO
    logger.importframework.additivity = false
    logger.importframework.appenderRef.rolling.ref = importAppender