{{- if default .Values.global.ingressEnabled .Values.ingress.enabled -}}
{{- $isTLSEnabled := .Values.ingress.tls.enabled -}}
{{- if $isTLSEnabled }}
{{- range .Values.ingress.tls.info }}
{{- if .secretName.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName.name }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  tls.crt: {{ .secretName.cert | b64enc }}
  tls.key: {{ .secretName.key | b64enc }}
type: kubernetes.io/tls
{{- end }}
{{- end }}
{{- end }}
{{- end }}