{{- if (or (not (hasKey .Values "vault")) (not (.Values.vault.enabled))) }}
  {{- if .Values.deploySecretsFromHelm -}}
  {{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.secretName }}
  {{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}-secret
  labels: {{ include "appworks-gateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if hasKey .Values "database" }}
  AWG_DB_PASSWORD: {{ .Values.database.appworksdb.password | b64enc }}
  {{- else }}
  AWG_DB_PASSWORD: {{ .Values.postgres.appworksdb.password | b64enc }}
  {{- end }}
  {{- if hasKey .Values.awg.settings.mail "smtpPassword" }}
  AWG_OTAG_SMTP_PASSWORD: {{ .Values.awg.settings.mail.smtpPassword | b64enc }}
  {{- end }}
  {{- if hasKey .Values.awg.settings.mail "oauthClientSecret" }}
  AWG_OTAG_OAUTH_CLIENT_SECRET: {{ .Values.awg.settings.mail.oauthClientSecret | b64enc }}
  {{- end }}

  {{- range .Values.tenants}}
  AWG_{{upper .name }}_DB_PASSWORD: {{ .database.appworksdb.password | b64enc }}
  {{- if hasKey .awg.settings.mail "smtpPassword" }}
  AWG_{{upper .name }}_OTAG_SMTP_PASSWORD: {{ .awg.settings.mail.smtpPassword | b64enc }}
  {{- end }}
  {{- if hasKey .awg.settings.mail "oauthClientSecret" }}
  AWG_{{upper .name }}_OTAG_OAUTH_CLIENT_SECRET: {{ .awg.settings.mail.oauthClientSecret | b64enc }}
  {{- end }}
  {{- end}}

  {{- end }}
  {{- end }}
  {{- end }}
