apiVersion: v1
kind: Service
metadata:
  name: {{ include "appworks-gateway.fullname" . }}
  labels:
    {{ include "appworks-gateway.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.annotations }}
      {{- if kindIs "map" .Values.service.annotations }}
        {{- range $key, $value := .Values.service.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- else if kindIs "slice" .Values.service.annotations }}
        {{- range .Values.service.annotations }}
        {{- . | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: 8080
  type: {{ default .Values.global.serviceType .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "appworks-gateway.name" . }}