apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ .Values.deployment.name }}-logging-configmap  
data:
  log4j2.properties: |
    status = {{ .Values.logging.rootLoggerLevel }}
    name = PropertiesConfig
    property.filename =  {{ .Values.logging.filename }}
    filter.threshold.type = ThresholdFilter
    monitorInterval = {{ .Values.logging.monitorInterval }}
    filter.threshold.level = {{ .Values.logging.rootLoggerLevel }}
    rootLogger.level = {{ .Values.logging.rootLoggerLevel }}
    rootLogger.appenderRefs = STDOUT, RollingFile
    rootLogger.appenderRef.stdout.ref = STDOUT
    rootLogger.appenderRef.rolling.ref = RollingFile
    appenders = console,rolling
    appender.console.type = Console
    appender.console.name = STDOUT
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %m%n
    appender.console.filter.threshold.type = ThresholdFilter
    appender.console.filter.threshold.level = {{ .Values.logging.consoleThresholdLevel }}
    appender.rolling.type = RollingFile
    appender.rolling.name = RollingFile
    appender.rolling.fileName = ${filename}
    appender.rolling.filePattern = ${filename}-%d{yyyy-MM-dd}-%i.log
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d %p %C{1.} [%t] %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
    appender.rolling.policies.time.interval = 2
    appender.rolling.policies.time.modulate = true
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size={{ .Values.logging.logFileSize }}
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = {{ .Values.logging.maxLogFiles }}
    loggers = rolling   
    logger.rolling.name = com.documentum.dctmreports
    logger.rolling.level = {{ .Values.logging.rootLoggerLevel }}
    logger.rolling.additivity = false
    logger.rolling.appenderRef.rolling.ref = RollingFile
 