#Replica count
replicaCount: 1
#Persistent volume
persistentVolume:
  size: 2Gi
  
#volumeClaimTemplates details
volumeClaimTemplates:
  size: 200Mi

#resources
resources:
  limits:
    cpu: 1000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 3Gi