# Default values for dctm-workflow-designer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#Prefix
prefix: <prefix>-dctm-workflow-designer

#Extra Init Containers
extraInitContainers:
  
#Docker image
image:
  repository: 
  name: <dctm-workflow-designer_image_path>
  tag: 25.4
  pullPolicy: 
  pullSecrets:

# Kubernetes Namespace in which this Helm chart is deployed
contextPath: DocumentumWorkflowDesigner
  
#persistentVolume details
persistentVolume:
  storageClass: 
  size: 200Mi
  pvcAccessModes: ReadWriteOnce
  #createPVC: true
  existingPVCName:
  PVCSubPath:
  awsEFS: false
  awsEFSCSIDriver: nfs.csi.k8s.io
  awsEFSCSIHandle:
  awsEFSCSIClaimPolicy: Retain
  existVolumePv:  

#Docbase Connection Info
docbaseConnection:
  use_certificate:
  truststorePassword: <truststore_password>
  docbroker: 
  port: 
  jmsport: 
  jmsprotocol: 
  #Name of the JMS Service. Refer JMS service name of type ClusterIP from CS Service Yaml
  jmsservicename:   
  docbase: 
  superUser: 
  superUserPassword: <password>
  globalRegistryRepository: 
  globalRegistryUsername: 
  globalRegistryPassword: <password>

#Volume used by CS and Broker to store CS and Broker certificates. Should match the persistentVolume name given in Broker values.yaml
dbrpersistentVolume:
  dbrdataPVCName: 
  
#Tomcat Admin credentials:
tomcat:
  javaOptions: <javaOptions>
  logfilerotation: 7 #Log files are rotated "logfilerotation" times before being removed
  logfilesize: 5M #Log files are rotated only if they grow bigger then "logfilesize" bytes
  logrotateFrequency: 1d #Log files are rotated every "logrotateFrequency". Ex., 10m, 10h, 10d 
  httpPort: 8080
  httpsPort: 8443


#CS Secret. Used to fetch TrustStore Password and Newrelic License Value
secret:
  name: 

otds:
  enable: 
  url:
  reverseproxy_url:
  client_id:
  client_secret:
  logon_appname:

#Newrelic agent configuration
newrelic:
  enable: 
  #Key Name of Newrelic License Key in CS Secrets. This value is referenced from yaml file of CS Secrets, needs to be changed accordingly.
  licenseKeyName: newrelicLicensekey
  app_name: <newrelic_app_name>
  proxy_host: 
  proxy_port: 
  
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
    #cpu: 1000m
    #memory: 4Gi
  #requests:
    #cpu: 500m
    #memory: 3Gi

serviceType:

liveness:
    initialDelay: 60
    timeout: 60
    period: 300
    failure: 2
readiness:
    initialDelay: 60
    timeout: 60
    period: 300
    failure: 2
    
#DFC properties:
#Below path should always be /home/xcpuser/<any_folder_name>
dfc:
  dataDir: /home/xcpuser/documentum

fsGroup:  

#Service Account
serviceAccount:
  createserviceaccount: true
  serviceAccountName: 
  
serviceAnnotations: {}

vault:
  enable: 
  vault_configmap: dctm-vault-configmap
  createPVC: false
  PVCName: dsis-binary-pvc
  pvcAccessModes: ReadWriteMany
  size: 100Mi
  storageClass: 
  existVolumePv:
  vault_config_mount_path: /opt/dctm_docker/vault_config
  binary_volume_mount_path: /opt/dctm_docker/dsis_binary_volume
  vault_timeout: 30
  statusCheckRetryCount: 20
  statusCheckTimeInterval: 1
  
#workflow designer CLI Info
workflowDesignercli:
  username: 
  # Enter password in the format Vault Secretname/Keyname if vault is enabled
  password: <password>
  repositoryName: 

trustStore:
  enable: false
  # Name of Workflow designer cli's Trust Store file, This Trust Store file should be kept inside dctm-workflow-designer/secrets folder
  fileName: <trustStoreFileName>
  # Password of the Trust Store 
  ingressPassword: 

#workflow designer cli parameters
workflowDesignerCliParam:
  # true/false, set true to override existing processes
  force: true

ui:
  idletime: 