apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "base.resource.name" . }}-configmap
data:
    ARTIFACT_VOLUMES_ROOT: /var/mkondo
    ACCESS_MODEL: getPublication
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    CLUSTER_DISCOVERY: kubernetes
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    ENABLE_OAUTH: 'true'
    EVENT_LOOP_POOL_SIZE: '4'
{{- if or .Values.global.enableOtivCustomizedTruststore .Values.global.otivSecretProviderClassCerts.enabled }}
    IV_TRUSTSTORE_PATH: /opt/certs/cacerts
{{- end }}    
{{- if .Values.auth.identityHeaders }}
    IDENTITY_HEADERS_LIST: '{{ .Values.auth.identityHeaders }}'
{{- end }}  
{{- if .Values.global.ipv6Enabled }}
    ENABLE_IPV6: 'true'
{{- end }}    
    LOG_OUT: {{ default .Values.global.logOutput .Values.logOutput }}
  {{- if .Values.loglevel.artifacts }}
    LOG_LEVEL_ARTIFACTS: {{ .Values.loglevel.artifacts }}
  {{- end }}
  {{- if .Values.loglevel.hazelCast }}
    LOG_LEVEL_HAZELCAST: {{ .Values.loglevel.hazelCast }}
  {{- end }}
  {{- if .Values.loglevel.netty }}
    LOG_LEVEL_NETTY: {{ .Values.loglevel.netty }}
  {{- end }}
  {{- if .Values.loglevel.system }}
    LOG_LEVEL_SYSTEM: {{ .Values.loglevel.system }}
  {{- end }}
  {{- if .Values.loglevel.vertx }}
    LOG_LEVEL_VERTX: {{ .Values.loglevel.vertx }}
  {{- end }}
  {{- if .Values.loglevel.vertxWebHandler }}
    LOG_LEVEL_VERTX_WEB_HANDLER: {{ .Values.loglevel.vertxWebHandler }}
  {{- end }}
    DISCOVERY_REGISTER_POLICY: name
    DISCOVERY_REGISTER_POLICY_NAME: {{ include "base.resource.name" . }}
    {{- template "new.relic.transform.config" . }}
    PEER_REST_PORT: '{{ .Values.service.port }}'
    PORT: '{{ .Values.service.targetPort }}'
    PUBLICATION_SERVICE_ORIGIN: http://otiv-publication:{{ .Values.publication.port }}
    {{- template "timezone" . }}
    VERTX_CLUSTER_NETWORK_PORT: '{{ .Values.global.hazelport }}'
    __VERSION__: '{{ template "version.stamp" . }}'
    
