{{- if or (include "is.ocp" .) .Values.global.istioVirtualServicesEnabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "base.resource.name" . }}
spec:
  hosts:
    - {{ include "ingress.fqdn.asset" .}}
    - {{ include "base.resource.name.svc" . }}
  gateways:
    - paas-apps/asm-gateway
    - mesh
  http:
    - route:
      - destination:
          host: {{ include "base.resource.name" . }}
{{- end }}
