# Default values for viewer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# error, warn, info, debug
loglevel: info
# fatal, error, warn, info, debug, trace
newRelic:
  loglevel: debug

replicas: 1

## hpa enabled at the global level
hpa:
  replicas:
    min: 1
    max: 3
  # the use of the targert type; valid values are utilization or averageValue
  #  defaults to global.hpa.targetType if not set
  targetType:
  # indicate whehter the cpu and memory targets are set. If not set, the global.hpa proerty values are used
  cpuTargetEnabled:
  memoryTargetEnabled:

  # values used if targetType set to utilization
  utilization:
    cpu: 70
    memory: 70
  # values used if targetType set to averageValue
  averageValue:
    cpu: 400m
    memory: 0.6Gi
  scaleDown:
    periodSeconds: 120
    stabilizationWindowSeconds: 300
  scaleUp:
    periodSeconds: 60
    stabilizationWindowSeconds: 300

image:
  name: otiv-markup

# The maximum number of SQL connections in the markup service pool; value must be greater than 0
dbMaxPoolSize: 10

database:
  name:

#command: '[ "tail",  "-f",  "/dev/null" ]'

pwdKey: DB_PWD

service:
  type: ClusterIP
  albType: NodePort
  port: 80
  targetPort: 3000
  # adds listed annotations to all otiv services
  # each entry needs to be a single string that contains a colon ( : ) that separates
  #   the property name and value
  annotations: []

resources:
  enabled: false
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 150
  initialDelaySecondsCS: 1800
  timeoutSeconds: 2
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 25
  failureThreshold: 2

## Available as of kubernetes version 1.16
startupProbe:
  enabled: true
  initialDelaySeconds: 45
  timeoutSeconds: 2
  periodSeconds: 30
  failureThreshold: 12
  failureThresholdCS: 80

ingress:
  enabled: true

# If set to true, Forwarded/X-Forwarded-Host header whitelist enforcement is enabled
#   and the services validate that the Forwarded/X-Forwarded-* headers adhere to what's 
#   allowed by the forwardedHostsList or forwardedHostsRegex properties.
#
# If set to true and the forwardedHostsList and forwardedHostsRegex are not defined 
#    or have been defined with an invalid syntax, the services will fail to start.
# If both of these properties are configured, forwardedHostsRegex takes precedence.
# The Forwarded/X-Forwarded-Host headers in incoming requests that do not match the
#    properties whitelist criteria are ignroed.
# If not defined here, corresponding global property values are used
#enforceForwardedHosts: false

# a comma seperated list of FQDNs (cannot specify protocols such as https) that are used
#   for validating the Forwarded/X-Forwarded-* headers.
#forwardedHostsList:

# a regex pattern to match FQDNs
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character, e.g.: .*site.sample.*
#forwardedHostsRegex:

# if set to true, requests will be only be accepted from the servers listed in corsOriginsList
#  or corsOriginsRegex; if both are defined, corsOriginRegex has precedence
# If not defined here, corresponding global property values are used
#enforceCorsOrigins: false

# a comma seperated list of servers that OTIV services will allow origin requests from
# each origin should start with https:// or http://
#corsOriginsList:

# a regex pattern for servers that OTIV services will allow origin requests from
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character. An example value would be: .*site.sample.*
#corsOriginsRegex:

# If set, the NODE_OPTIONS env variable will be set with the value
nodeOptions:

# If true, requires an integrator provided JWT to authorize access to markups
enableRoleBasedAccessControl: false

# string used for generating a key to sign access control JWT
jwtSecret:
