#xDA PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix}}-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  storageClassName: {{ .Values.persistentVolume.storageClassReadWriteOnce | default .Values.global.rwoStorage }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}