################################################################################################
#                                                                                              #
#                                   This is a YAML-formatted file.                             #
#                          Provide the values for variables to be passed to the templates.     #
################################################################################################

##################################################################################################################                                                                                                                                                                                    #
#                                 READ ME FIRST: General information about this YAML file.                       #
# This YAML file defines the Kubernetes secret object used to securely store sensitive data such as passwords.   # 
# Make sure that you apply the secrets to the cluster before deploying, upgrading, or migrating OpenText         #
# Documentum Content Management (CM) Helm charts that depend on these secrets.                                   #
#                                                                                                                #
# IMPORTANT:                                                                                                     #
# Use the stringData variable to specify the secret keys and their corresponding password values in plain text.  #
# Kubernetes converts the password values to the Base64-encoded format automatically.                            # 
# Each key in stringData corresponds to the secret key names referenced as values in the                         #
# passwords_k8api.yaml file so that this key match with values in the passwords_k8api.yaml file.                 #
#                                                                                                                #
# CAUTION:                                                                                                       # 
# Do not change existing key names.                                                                              #
#                                                                                                                #
# Note:                                                                                                          #
# If you want to add new keys, follow the following naming conventions:                                          #
# 1. Use only lowercase alphanumeric characters, hyphens (-), underscores (_), and dots (.).                     #
# 2. Keys must start and end with an alphanumeric character.                                                     #
# 3. Avoid spaces, uppercase letters, or special characters like @, #,/, or $.                                   #
##################################################################################################################

apiVersion: v1
kind: Secret
metadata:
  # Description: Unique name for the secret.
  name: vault-secret-config
  namespace: 
type: Opaque
stringData:
  # Description: Password for the Documentum client privileged client utility user. Use the installation owner password and 
  # replace <docbase_name> with the actual repository name before the deployment process.
  <docbase_name>-D2_UTILITY_USER_PASSWORDS:

  # Description: Password for the Admin Console privileged client utility user. Use the installation owner password and 
  # replace <docbase_name> with the actual repository name before the deployment process.
  <docbase_name>-ADMIN_CONSOLE_UTILITY_USER_PASSWORDS:

  # Description: Crypto salt for client token encryption/decryption (must be same across all REST, Admin Console, Smart View services in multi-node. 
  # This is optional for single-node and should be up to 8 ASCII characters.
  DCTM_REST_CLIENT_TOKEN_SALT:

  # Description: Passphrase to protect the AEK file.
  aekPassphrase: 
  
  # Description: OTDS administrator password.
  otdsAdminPassword: 
  
  # Description: Password to access the database.
  dbPassword: 
  
  # Description: Administrator password of the application server.
  installAppserverAdminPassword: 
  
  # Description: Password of the global registry user.
  globalRegistryPassword: 
  
  # Description: Password to connect to the repository.
  docbasePassword: 
  
  # Description: Password of the installation owner.
  installOwnerPassword: 
  
  # Description: Password of the installation root directory.
  rootPassword: 
  
  # Description: Documentum CM Server keystore password.
  csCertPassword: 
  
  # Description: Password of the trust store.
  trustStorePassword: 
  
  # Description: Documentum CM Server trust store password.
  csCertTrustPassword: 
  
  # Description: Connection broker passphrase to protect the AEK file.
  dbrCertAekPassphrase:

  # Description: Connection broker trust store password.
  dbrCertTrustPassword: 
  
  # Description: Connection broker keystore password.
  dbrCertpassword: 
  
  # Description: Service account password to connect to Reports.
  drServiceAccountPassword:
  
  # Description: Service account user name to connect to Reports.
  drServiceAccountUser: 
  
  # Description: Contents of the JSON file generated on Google Cloud store.
  gcpStorecredentials: 
  
  # Unsupported feature
  kmsApiKey: 
  
  # Description: Microsoft Azure app registration client secret for Documentum Content Management for Microsoft 365.
  m365ClientSecret:
  
  # Description: Older AEK passphrase.
  oldaekPassphrase:   
 
  # Description: Preset password information.
  CLIENTS_PRESET_PASSWORD:
 
  # Description: Preference password information.
  CLIENTS_PREFERENCE_PASSWORD:
  
  # Description: Name of the user accessing the REST store. Use the REST Tenant Owner.
  # Note: The value for this variable is not required for Google Cloud store.
  # To use vault, provide the Microsoft Azure credential secret ID.
  restStoreCredentialID: 
  
  # Description: Password of the user accessing the REST store. Use the Object Access Key.
  # Note: The value for this variable is not required for Google Cloud store.
  # To use vault, provide the Microsoft Azure credential key.
  restStoreCredentialKEY: 
  
  # Description: Name of the user accessing the S3 store. Use the S3 Tenant Owner. 
  # To use vault, provide the S3 store credential secret ID.
  s3StoreCredentialID: 
  
  # Description: Password of the user accessing the S3 store. Use the Object Access Key. 
  # To use vault, provide the S3 store credential key.
  s3StoreCredentialKEY: 
  
  # Description: Password of the user to access the SMTP server.
  smtpPass: 
  
  # Description: Certificate information of the SMTP server.
  smtpSSLCertificate: 

  # Description: Password information.
  m365clientsecret:
  
  # Description: Solr authentication password used to connect to Solr.
  solr_auth_password: 
  
  # Description: Solr password used to connect to ZooKeeper.
  solr_zk_password: 
  
  # Description: Password to connect to ZooKeeper.
  zk_password: 
  
  # Description: Branch Office Caching Services keystore password.
  DCTM_BOCS_KEYSTORE_PASSWORD:
  
  # General Information: The following OTDS secrets are required only if OTDS is enabled (otds.enabled=true).
  # =========================================================================================================
  
  # Description: OTDS administrator user password. 
  OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD:
  
  # Description: OTDS database user name.
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER:
  
  # Description: OTDS database password.
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD:
  
  # Description: Used for secure and synchronized access to the backend database from the
  # frontend instances. The value is a 16-character ASCII string that has been Base64-encoded, and
  # must be double Base64 encoded.
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: 
  
  # General Information: The following OTIV secrets are required only if OTIV is enabled (otiv.enabled=true).
  # =========================================================================================================
  
  # Description: Key for the RabbitMQ broker password. 
  rabbitmq-password: 
  
  # Description: Intelligent Viewing database administrator password. 
  OTIV_DB_ADMIN_PASSWORD: 
  
  # Description: Intelligent Viewing database password. 
  OTIV_DB_PASSWORD:
  
  # Description: OTDS administrator password.
  ADMIN_USER_PASSWORD:
  
  # Description: PostgreSQL database password. The value for this key is required only if PostgreSQL is enabled in the subchart.
  postgres-password:
  
  # Description: Key for the highlight service OAuth client secret.
  OTIV_HIGHLIGHT_CLIENT_SECRET:
  
  # Description: Key for the OAuth client secret used for monitoring.
  OTIV_MONITOR_CLIENT_SECRET:
  
  # Description: Key for the publication service OAuth client secret.
  OTIV_PUBLICATION_CLIENT_SECRET:
  
  # Description: Key for the publishing agent OAuth client secret.
  OTIV_PUBLISHER_CLIENT_SECRET: 
  
  # General Information: The following AppWorks Gateway secrets are required only if AppWorks Gateway is enabled within chart (appworks-gateway.enabled=true).
  # ==========================================================================================================================================================

  # Description: AppWorks Gateway database administrator password required for PostgreSQL (Postgres Admin password).
  AWG_DB_ADMIN_PASSWORD: 

  # Description: AppWorks Gateway database password.
  AWG_DB_PASSWORD: 

  # Description: Password to sign in to the AppWorks Gateway Administration user interface. Make sure that the password meets the OTDS global password policy.
  AWG_GATEWAY_NEW_ADMIN_PASSWORD:

  # Description: Password of the OpenText Directory Services (OTDS) administrator.
  AWG_OTDS_ADMIN_PASSWORD:

  # Description: AppWorks Gateway SMTP mail password.
  AWG_OTAG_SMTP_PASSWORD:

  # Description: AppWorks Gateway OAuth mail client secret.
  AWG_OTAG_OAUTH_CLIENT_SECRET:

  #==========================================================================================

  # Description: Password of the Java Management Extensions (JMX) server.
  JmxPassword:
  
  # Description: ActiveMQ password.
  DS_AMQ_PASSWORD: 
  
  # Description: Documentum CM Search administrator password.
  DS_ADMIN_PASSWORD: 
  
  # Description: New Relic license key.
  newrelicLicenseKey: 
  
  # Description: Advanced Workflow user password.
  xDA_DAW_PASSWORD: 
  
  # Description: Administrator password used to communicate among the replicas in the Apache Kafka cluster.
  kafka-password:
  
  # Description: Password of the user to access the SMTP server.
  DOCBASE_SMTP_PASSWORD: 
  
  # Unsupported feature
  OTKMS_CREDENTIALS: 
  
  # Description: Encrypted database password for OES connectors.
  OES_DATABASE_PASSWORD: 
  
  # Description: Encrypted OES client secret for OES connectors.
  OES_CLIENT_SECRET:
  
  # Description: Encrypted database password for the notification service.
  NS_DBPASSWORD:
  
  # Description: Keystore password.
  keystorePassword:
  
  # Description: Keystore password of the repository.
  docbaseCertPassword:
  
  # Description: Value of the key to retrieve the Content Connect database password.
  CC_DBPASSWORD:
  
  # Description: Value of the key to retrieve the Documentum Connector for Core Share database password.
  DCC_DATABASE_PASSWORD:
  
  # Description: Encrypted client secret generated from Documentum Connector for Core Share administrator.
  DCC_TARGET_REPO_CLIENT_SECRET:
  
  # Description: Encrypted password from the Documentum Content Management superuser repository.
  DCC_SOURCE_REPO_PASSWORD:
  
  # Description: If authenticationType is basic and SMTP server requires credentials, provide the encrypted password for the server.
  # To use vault, provide the secret name to retrieve the password.
  DCC_MAIL_PASSWORD:
  
  # Description: Password of the SAP ILM administrator user.
  ilm_user_password:

  # Description: Password used by the users of OpenText Content Management for the SOAP Configuration.
  soap_config_auth_password:
  
  # Description: Ingress keystore password to enable the backend TLS.
  ingressKeystorePassword: 
  
  # Description: Trust store password for the common trust store creation.
  commonTruststorePassword:

  # General Information: The following LSS secrets are required only if LSS is enabled (lss.enabled=true).
  # =========================================================================================================
  
  # Description: Password for the iHub service admin user.
  ihubServicePasswordKey:

  # Description: Password for the sftp default admin user.
  lsSftpAdminPasswordKey: 

