apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName | default .Values.global.dmsServiceName }}-configmap-dfc

data:
  dfc.properties: |
    dfc.data.dir={{ .Values.dfc.dataDir }}
    dfc.docbroker.host[0]={{ .Values.dfc.docbroker | default .Values.global.dbrServiceName }}.{{ .Values.dfc.clusterSpace | default (include "documentum.envDomain" .)}}
    dfc.docbroker.port[0]={{ .Values.dfc.port | default .Values.global.dbr_port }}
    dfc.security.ssl.truststore={{ .Values.dfc.certificate.truststore }}
    dfc.security.ssl.truststore_password={dfcSecuritySslTruststorePassword}
    dfc.security.ssl.use_existing_truststore={{ .Values.dfc.certificate.use_existing_truststore }}
    dfc.crypto.repository={{ .Values.dfc.cryptoRepository | default .Values.global.docbase }}
    dfc.globalregistry.repository={{ .Values.dfc.globalRegistryRepository | default .Values.global.docbase }}
    dfc.globalregistry.username={{ .Values.dfc.globalRegistryUsername | default .Values.global.globalRegistryUsername }}
    {{- range .Values.dfc.additionalProperties }}
    {{ . }}
    {{- end }}