{{if (empty (.Values.newrelic.enabled | quote) | ternary .Values.global.newrelic .Values.newrelic.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName | default .Values.global.dmsServiceName }}-configmap-newrelic
data:
  {{ .Values.newrelic.configurationFile }}: |
{{ .Files.Get .Values.newrelic.configurationFile  | indent 4 }}
{{- end }}