# This secret is used for CS, DB

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace:  {{ .Values.secret.namespace | default .Release.Namespace }}
type: Opaque
data:
  jmxPassword: {{ .Values.jmx.password | b64enc | quote }}
  bocsssl: {{ default "" .Values.certificates.bocsssl | b64enc | quote }}
