apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.resource.name" . }}
  {{- template "metadata.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    helm.sh/chart: {{ include "brava.chart" . }}
    app.kubernetes.io/instance: {{ include "base.resource.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- template "otiv.service.annotations" . }}
spec:
{{- if eq .Values.global.ingressClass "alb" }}
  type: {{ .Values.service.albType }}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ include "base.resource.name" . }}
    app: {{ include "base.resource.name" . }}
