 # VE #4852332 - Adding the service account details
{{- if .Values.assapilm.serviceAccount.createserviceaccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.assapilm.serviceAccount.serviceAccountName | default  .Values.global.documentumserviceaccount}}
  namespace: {{ .Values.namespace }}
{{- end }}