# VE# 4852332 - Added the documentum useCSDfcConfigMap support
{{- if eq .Values.cs.useCSDfcConfigMap false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-dfcproperties-configmap
data:
  dfc.properties: |
   {{- range .Values.dfc.properties }}
   {{ . }}
   {{- end }}
{{ end }}