apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ .Values.deployment.name }}-dmsapilm-configmap
data:
  DmSapILM.properties: |
    Version=1.0
    SAPILM.admin.username={{ .Values.global.installOwnerUsername }}
    SAPILM.admin.password=&SAPILM_ADMIN_PASSWORD&
    CenteraRetentionAttribute={{ .Values.dmsapilm.centeraRetentionAttribute }}
    forceEmptyCollectionDelete={{ .Values.dmsapilm.forceEmptyCollectionDelete }}
    SAPILM.admin.runHybrid={{ .Values.dmsapilm.sapilmAdminRunhybrid }}
    SAPILM.admin.timeInMsForProppatchStart={{ .Values.dmsapilm.sapilmAdminTimeinmsforproppatchstart }}
    SAPILM.admin.forceUnknowRetentionUpdate={{ .Values.dmsapilm.sapilmAdminForceunknowretentionupdate }}
    SAPILM.admin.IlmUserPassword=&SAPILM_ADMIN_ILMUSERPASSWORD&