{{- if eq .Values.ingress.enable true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: {{ .Values.ingress.name }}.{{ .Values.ingress.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: {{ .Values.service.port }}
{{ end }}
