#Leave below value as empty if the deployment is not aws. if aws, follow cloud deployment guide to use aws.yaml
platform:
#prefix for the ingress name
ingressPrefix: <prefix>
ingress:   
  #No need to configure host: and clusetrDomainName: if configureHost is false.
  configureHost: true
  #Domain name of the ingress controller in the cluster namespace
  host: 
  clusterDomainName: 
  #To accomodate cluster 1.22
  class: nginx
  #annotations for the ingress object
  annotations: {}
  #secret to be set when the InternalTLSflag is enabled
  ingressTLSSecret:
  
# The application URLs will be in the format of <PROTOCOL>://<INGRESS-HOSTNAME>.<CLUSTER-DOMAIN-NAME>/<APPLICATION PATH>
# Ex: if the value of INGRESS-HOSTNAME is 'prod' and CLUSTER-DOMAIN-NAME value is 'docu.cfcr-lab.bp-paas.otxlab.net' 
# then to access ACS application, the URL will be some thing like http://prod.docu.cfcr-lab.bp-paas.otxlab.net/ACS/servlet/ACS

jmsService:
  enable: 
  serviceName:
  servicePort: 9080
  pathType:

jmsBase:
  enable: false
  serviceName: 
  servicePort: 9080
  pathType:

ijms:
  serviceName: <ijms-service-name>
  servicePort:
  path: ijms
  pathType:

acsService:
  enable: 
  serviceName:
  servicePort: 9080
  pathType:
  
tnsService:
  enable: 
  serviceName: <tns-service-name>
  servicePort: 8081
  pathType:

d2clientService:
  enable: 
  serviceName: <d2client-service-name>
  path: 
  pathType:

d2configService:
  enable: 
  serviceName: <d2config-service-name>
  path: 
  pathType:

daService:
  enable: 
  serviceName: <da-service-name>
  servicePort: 8080
  pathType:
restService:
  enable: 
  serviceName: <dctm-rest-service-name>
  pathType:

bpsService:
  enable: false
  serviceName: <bps-service-name>
  servicePort: 8080
  pathType:

xdaService:
  enable: 
  serviceName: <xda-service-name>
  servicePort: 7000
  pathType:
smartviewm365:
  enable: 
  serviceName: <smartviewm365-service-name>
  servicePort: 8080
  path: /SmartViewM365
  pathType:

dsearchadminService:
  enable: false
  serviceName: <dsearchadmin-service-name>
  servicePort: 9300
  pathType:

documentumSearchService:
  enable: 
  serviceName: <documentumSearch-service-name>
  servicePort: 8800
  path: /admin
  pathType:

indexagentService:
  enable: false
  serviceName: <indexagent-service-name>
  servicePort: 9200
  pathType:
dfsService:
  enable: 
  serviceName: <dfs-service-name>
  servicePort: 8080
  pathType:

dmsService:
  enable: 
  serviceName:
  servicePort:
  pathType:

cmisService:
  enable: 
  serviceName: <cmis-service-name>
  servicePort: 8080
  pathType:

webtopService:
  enable: false
  serviceName: <webtop-service-name>
  servicePort: 8080
  pathType:

dmotdsrestService:
  enable: 
  serviceName:
  servicePort: 9080
  pathType:

otdsadmin:
  enable: 
     #Name of the otds service.
  serviceName: <otdsServiceName>
     #otds clusterIP service port. Default 80
  servicePort: 80
  pathType:

otdsws:
  enable: 
     #Name of the otds service.
  serviceName: <otdsServiceName>
     #otds clusterIP service port. Default 80
  servicePort: 80
  pathType:

otdstenant:
  enable: false
     #Name of the otds service.
  serviceName: <otdsServiceName>
     #otds clusterIP service port. Default 80
  servicePort: 80
  pathType:
  
### enable TLS ###
tls:
  enable: false
  secretName:

openshifttls:
  enable:
  
dtrbaseService:
  enable: false
  serviceName: dtrbase
  servicePortCore: 5001
  servicePortServlet: 8080
  
workflowDesignerService:
  enable: 
  serviceName: <dctm-workflow-designerServiceName>
  servicePort: 9080

bpm:
   enable: false
   #Name of the jms clusterIp service. Refer CS Service Yaml
   serviceName:
   #bpm clusterIP service port. Default 9080
   servicePort: 9080

recordsService:
  enable: 
  serviceName: records-svc
  servicePort: 8080
  
d2smartview:
  enable: 
  serviceName: d2smartview
  path: 
  
d2rest:
  enable: 
  serviceName: d2rest
  path: 
  
dcc:
  enable: 
  prefix: dcc
  consul:
    prefix: consul
    service:
      servicePort: 8500    
  syncagent:
    enabled: 
    prefix: syncagent
    service:
      servicePort: 8080    
  syncnshareManual:
    enabled: 
    prefix: syncagent-manual
    service:
      servicePort: 8080
      
ccService:
  enabled: 
  serviceName: cc
  servicePort: 8080
  extension: cc
  pathType:

ccadminService:
  enabled:  
  serviceName: cc-admin
  servicePort: 80
  extension: cc
  pathType:

epfmaService:
  enable: 

dc4spService:
  enable: false
  host: lss-pub-dc4sp
  serviceName: dc4sp-svc

d2xmlViewerService:
  enable: false
  serviceName: <d2client-service-name>
  path: XMLViewer

d2lsService:
  enable: false
  serviceName: <d2client-service-name>
  path: d2ls

lsprintService:
  enable: false
  serviceName: lsprint-svc
  path: ControlledPrint

lssftpService:
  enable: false
  serviceName: sftp-svc
  path: sftp-users-management

adminconsole:
  enable: 
  serviceName: adminconsole
  path: 
  pathType:

oesconnector:
  enable: 
  serviceName: oes
  servicePort: 8080
  path: oes-connector
  pathType:

assapservice:
  enable: 
  serviceName: assap-svc
  servicePort: 8080
  path: assap
  pathType:

cssapservice:
  enable: 
  serviceName: cssap-svc
  servicePort: 8080
  path: HvpWorker/hvpCommand
  pathType:

assapilmservice:
  enable: 
  serviceName: assap-ilm-svc
  servicePort: 8080
  path: dmwebdav
  pathType:

  
#extraPaths is used to define additional ingress resources for D2 customizations
#For aws path should be as follows path: /CustomApp1*
#extraPaths:
#      - backend:
#          serviceName: {{ .Values.d2webappName }}
#          servicePort: 8080        
#        path: /CustomApp1

   
adminURLS:
     #On enabling this, enable one of the below services also
  enable: false
  ingressPrefix: ceadminingress
  #No need to configure host: and clusetrDomainName: if configureHost is false.
  configureHost: true
  ingress:
         #Domain name of the ingress controller in the cluster namespace
    host: <INGRESS-HOSTNAME>
    clusterDomainName: <CLUSTER-DOMAIN-NAME>
    #To accomodate cluster 1.22 
    class: nginx
    #annotations for the ingress object
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"      
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "60" 
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.org/hsts: "false"
  daService:
    enable: false
    serviceName: <da-service-name>
    servicePort: 8080  
  indexagentService:
    enable: false
    serviceName: <indexagent-service-name>
    servicePort: 9200
     ### enable TLS ###
  tls:
    enable: true
    secretName: cecs-secret-config
