apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.resource.name" . }}-configmap
  {{- template "metadata.namespace" . }}
data:
    AJIRA_PORT: {{ include "amqp.port" . }}
    AJIRA_USE_SSL: '{{ .Values.global.amqp.ssl }}'
{{- if and .Values.global.amqp.ssl (not .Values.global.enableOtivCustomizedTruststore) (not .Values.global.otivSecretProviderClassCerts.enabled) }}
    AJIRA_KEYSTORE_PATH: /opt/jre/lib/security/cacerts
    AJIRA_TRUSTSTORE_PATH: /opt/jre/lib/security/cacerts
{{- end }}
{{- if and .Values.global.amqp.ssl (or .Values.global.enableOtivCustomizedTruststore .Values.global.otivSecretProviderClassCerts.enabled ) }}
    AJIRA_KEYSTORE_PATH: /opt/certs/cacerts
    AJIRA_TRUSTSTORE_PATH: /opt/certs/cacerts
{{- end }}
{{- if or .Values.global.enableOtivCustomizedTruststore .Values.global.otivSecretProviderClassCerts.enabled }}
    IV_TRUSTSTORE_PATH: /opt/certs/cacerts
{{- end }}
{{- if .Values.global.ipv6Enabled }}
    ENABLE_IPV6: 'true'
{{- end }}    
{{- if .Values.global.cssFqdn }}
    ARTIFACT_DELIVERY_LEAP_CSS_WHITELIST: {{ include "css.whitelist" .}}
    ARTIFACT_DELIVERY_PROFILE: leap
    BLOB_SERVICE_URL: {{ .Values.global.cssProtocol }}://{{ .Values.global.cssFqdn }}
    MARKUP_SERVICE_ORIGIN: http://cvt-markup:{{ .Values.markup.port }}
    METRICS_PROVIDER: "newrelic"
{{- else }}
    AJIRA_HOST: {{ .Values.global.amqp.host }}
    AJIRA_USER: {{ .Values.global.amqp.user }}
    AJIRA_VHOST: {{ .Values.global.amqp.vhost }}
    AJIRA_RECONNECT_ATTEMPTS: '{{ .Values.global.amqp.reconnectAttempts }}'
    ARTIFACT_DELIVERY_PROFILE: mkondo
    METRICS_PROVIDER: {{ .Values.metricsProvider }}
    MKONDO_BLOB_BASE_URL: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn.asset" .}}/artifacts
    MARKUP_SERVICE_ORIGIN: http://otiv-markup:{{ .Values.markup.port }}
    MKONDO_BLOB_ROOTS: /var/mkondo/fs-0
    MKONDO_STORAGE_DISABLED: 'false'
{{- end }}
    CLUSTER_DISCOVERY: kubernetes
    COUNTER: '{{ .Values.global.counter }}'
{{- if .Values.cssUploadTimeout }}
    CSS_UPLOAD_TIMEOUT_SECONDS: '{{ .Values.cssUploadTimeout }}'
{{- end }}
    ENABLE_OAUTH: 'true'
    EVENT_LOOP_POOL_SIZE: '8'
{{- if .Values.fipsEnabled }}
    FIPS_ENABLED: 'true'
{{- end }}
    LOG_OUT: {{ include "log.output" . }}
{{- if .Values.writeMarkups }}
    WRITE_MARKUPS: '{{ .Values.writeMarkups }}'
{{- end }}
{{- if .Values.loglevel.artifacts }}
    LOG_LEVEL_ARTIFACTS: {{ .Values.loglevel.artifacts }}
{{- end }}
{{- if .Values.loglevel.config }}
    LOG_LEVEL_CONFIG: {{ .Values.loglevel.config }}
{{- end }}
{{- if .Values.loglevel.conversion }}
    LOG_LEVEL_CONVERSION: {{ .Values.loglevel.conversion }}
{{- end }}
{{- if .Values.loglevel.discovery }}
    LOG_LEVEL_DISCOVERY: {{ .Values.loglevel.discovery }}
{{- end }}
{{- if .Values.loglevel.metrics }}
    LOG_LEVEL_METRICS: {{ .Values.loglevel.metrics }}
{{- end }}
{{- if .Values.loglevel.netty }}
    LOG_LEVEL_NETTY: {{ .Values.loglevel.netty }}
{{- end }}
{{- if .Values.loglevel.retrieval }}
    LOG_LEVEL_RETRIEVAL: {{ .Values.loglevel.retrieval }}
{{- end }}
{{- if .Values.loglevel.sequencing }}
    LOG_LEVEL_SEQUENCING: {{ .Values.loglevel.sequencing }}
{{- end }}
{{- if .Values.loglevel.spi }}
    LOG_LEVEL_SPI: {{ .Values.loglevel.spi }}
{{- end }}
{{- if .Values.loglevel.spiAjira }}
    LOG_LEVEL_SPI_AJIRA: {{ .Values.loglevel.spiAjira }}
{{- end }}
{{- if .Values.loglevel.hazelCast }}
    LOG_LEVEL_HAZELCAST: {{ .Values.loglevel.hazelCast }}
{{- end }}
{{- if .Values.loglevel.spiMkondo }}
    LOG_LEVEL_SPI_MKONDO: {{ .Values.loglevel.spiMkondo }}
{{- end }}
{{- if .Values.loglevel.spiPithos }}
    LOG_LEVEL_SPI_PITHOS: {{ .Values.loglevel.spiPithos }}
{{- end }}
{{- if .Values.loglevel.spiSoteria }}
    LOG_LEVEL_SPI_SOTERIA: {{ .Values.loglevel.spiSoteria }}
{{- end }}
{{- if .Values.loglevel.system }}
    LOG_LEVEL_SYSTEM: {{ .Values.loglevel.system }}
{{- end }}
{{- if .Values.loglevel.util }}
    LOG_LEVEL_UTIL: {{ .Values.loglevel.util }}
{{- end }}
{{- if .Values.loglevel.vertx }}
    LOG_LEVEL_VERTX: {{ .Values.loglevel.vertx }}
{{- end }}
{{- if .Values.loglevel.zmq }}
    LOG_LEVEL_ZMQ: {{ .Values.loglevel.zmq }}
{{- end }}
    {{- template "new.relic.transform.config" . }}
    PITHOS_HOST: {{ .Values.global.database.hostname }}
    PITHOS_PROVIDER: {{ .Values.global.database.type }}
    PITHOS_PORT: '{{ .Values.global.database.port }}'
    PITHOS_DB: {{ .Values.global.database.ivName }}
{{- if (include "is.iv" .) }}
    AUTH_CLIENT_ID: {{ .Values.clientId }}
    DB_ADMIN_USER: {{ .Values.global.database.adminUsername }}
    PITHOS_ADMIN_DB: {{ .Values.global.database.adminDatabase }}
    PITHOS_USER: {{ .Values.global.database.ivUsername }}
{{- end }}
    PITHOS_USE_SSL: '{{ .Values.global.database.ssl }}'
    PITHOS_SSL_MODE: '{{ .Values.global.database.sslMode }}'
    INTERNAL_REST_PORT: '{{ .Values.service.targetPort }}'
{{- if .Values.global.database.oracleConnectOptions }}
    PITHOS_ORACLE_CONNECT_OPTIONS: '{{ .Values.global.database.oracleConnectOptions }}'
{{- end }}
    PITHOS_KEYSTORE_TYPE: 'JKS'
{{- if and .Values.global.database.ssl (not .Values.global.enableOtivCustomizedTruststore) (not .Values.global.otivSecretProviderClassCerts.enabled) }}
    PITHOS_KEYSTORE_PATH: /opt/jre/lib/security/cacerts
    PITHOS_TRUSTSTORE_PATH: /opt/jre/lib/security/cacerts
{{- end }}
{{- if and .Values.global.database.ssl (or .Values.global.enableOtivCustomizedTruststore .Values.global.otivSecretProviderClassCerts.enabled) }}
    PITHOS_KEYSTORE_PATH: /opt/certs/cacerts
    PITHOS_TRUSTSTORE_PATH: /opt/certs/cacerts
{{- end }}
    {{- template "proxy.url.params" . }}
    SOTERIA_PROVIDER: otds
    {{- template "timezone" . }}
    {{- template "trusted.source.origins" . }}
    {{- template "publisher.secret.keys" . }}
    VERTX_CLUSTER_NETWORK_PORT: '{{ .Values.global.hazelport }}'
    __VERSION__: '{{ template "version.stamp" . }}'
