apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-configmap

data:
{{- if or .Values.ssl.enabled .Values.global.useCertificate }}
  jms.host: {{ .Values.service.name }}
  jms.port: {{ .Values.ssl.acceptorPort | quote }}
  jms.url: >-
    tcp://{{ .Values.service.name }}:{{ .Values.ssl.acceptorPort }}?jms.redeliveryPolicy.maximumRedeliveries=1&group-rebalance=true&group-rebalance-pause-dispatch=true
{{- else }}
  jms.host: {{ .Values.service.name }}
  jms.port: {{ .Values.service.broker.ports.external.openwire | quote }}
  jms.url: >-
    tcp://{{ .Values.service.name }}:{{ .Values.service.broker.ports.external.openwire }}?jms.redeliveryPolicy.maximumRedeliveries=1&group-rebalance=true&group-rebalance-pause-dispatch=true
{{- end }}
{{- if or .Values.ssl.enabled .Values.global.useCertificate }}
  broker.xml: |-
    <configuration xmlns="urn:activemq"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:xi="http://www.w3.org/2001/XInclude"
                   xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">

      <core xmlns="urn:activemq:core" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:activemq:core ">

        <name>0.0.0.0</name>
        <persistence-enabled>true</persistence-enabled>
        <max-redelivery-records>1</max-redelivery-records>
        <journal-type>NIO</journal-type>

        <paging-directory>data/paging</paging-directory>
        <bindings-directory>data/bindings</bindings-directory>
        <journal-directory>data/journal</journal-directory>
        <large-messages-directory>data/large-messages</large-messages-directory>

        <journal-datasync>true</journal-datasync>
        <journal-min-files>2</journal-min-files>
        <journal-pool-files>10</journal-pool-files>
        <journal-device-block-size>4096</journal-device-block-size>
        <journal-file-size>10M</journal-file-size>
        <journal-buffer-timeout>312000</journal-buffer-timeout>
        <journal-max-io>1</journal-max-io>
        <disk-scan-period>5000</disk-scan-period>
        <max-disk-usage>90</max-disk-usage>
        <critical-analyzer>true</critical-analyzer>
        <critical-analyzer-timeout>120000</critical-analyzer-timeout>
        <critical-analyzer-check-period>60000</critical-analyzer-check-period>
        <critical-analyzer-policy>HALT</critical-analyzer-policy>

        <page-sync-timeout>312000</page-sync-timeout>
        <global-max-messages>-1</global-max-messages>

        <!-- Acceptors -->
        <acceptors>
             <!-- Non-SSL acceptors -->
          <acceptor name="artemis">tcp://0.0.0.0:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;amqpMinLargeMessageSize=102400;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpDuplicateDetection=true;supportAdvisory=false;suppressInternalManagementObjects=false</acceptor>
          <acceptor name="amqp">tcp://0.0.0.0:5672?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=AMQP;useEpoll=true;amqpCredits=1000;amqpLowCredits=300;amqpMinLargeMessageSize=102400;amqpDuplicateDetection=true</acceptor>
          <acceptor name="stomp">tcp://0.0.0.0:61613?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=STOMP;useEpoll=true</acceptor>
          <acceptor name="hornetq">tcp://0.0.0.0:5445?anycastPrefix=jms.queue.;multicastPrefix=jms.topic.;protocols=HORNETQ,STOMP;useEpoll=true</acceptor>
          <acceptor name="mqtt">tcp://0.0.0.0:1883?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=MQTT;useEpoll=true</acceptor>

             <!-- âœ… SSL acceptor -->
          <acceptor name="ssl-acceptor">tcp://0.0.0.0:${ACCEPTOR_PORT}?sslEnabled=true;protocols=CORE,AMQP,OPENWIRE;keyStorePath=${KEYSTORE_LOCATION};keyStorePassword=${KEYSTORE_PASSWORD};trustStorePath=${TRUSTSTORE_LOCATION};trustStorePassword=${TRUSTSTORE_PASSWORD};needClientAuth=false</acceptor>
        </acceptors>

        <!-- Security -->
        <security-settings>
          <security-setting match="#">
            <permission type="createNonDurableQueue" roles="admins,amq"/>
            <permission type="deleteNonDurableQueue" roles="admins,amq"/>
            <permission type="createDurableQueue" roles="admins,amq"/>
            <permission type="deleteDurableQueue" roles="admins,amq"/>
            <permission type="createAddress" roles="admins,amq"/>
            <permission type="deleteAddress" roles="admins,amq"/>
            <permission type="consume" roles="admins,amq"/>
            <permission type="browse" roles="admins,amq"/>
            <permission type="send" roles="admins,amq"/>
            <permission type="manage" roles="admins"/>
          </security-setting>
        </security-settings>

        <!-- Address settings -->
        <address-settings>
          <address-setting match="activemq.management#">
            <dead-letter-address>DLQ</dead-letter-address>
            <expiry-address>ExpiryQueue</expiry-address>
            <redelivery-delay>0</redelivery-delay>
            <max-size-bytes>-1</max-size-bytes>
            <message-counter-history-day-limit>10</message-counter-history-day-limit>
            <address-full-policy>PAGE</address-full-policy>
            <auto-create-queues>true</auto-create-queues>
            <auto-create-addresses>true</auto-create-addresses>
          </address-setting>
          <address-setting match="#">
            <dead-letter-address>DLQ</dead-letter-address>
            <expiry-address>ExpiryQueue</expiry-address>
            <redelivery-delay>0</redelivery-delay>
            <message-counter-history-day-limit>10</message-counter-history-day-limit>
            <address-full-policy>PAGE</address-full-policy>
            <auto-create-queues>true</auto-create-queues>
            <auto-create-addresses>true</auto-create-addresses>
            <auto-delete-queues>false</auto-delete-queues>
            <auto-delete-addresses>false</auto-delete-addresses>
            <page-size-bytes>10M</page-size-bytes>
            <max-size-bytes>-1</max-size-bytes>
            <max-size-messages>-1</max-size-messages>
            <max-read-page-messages>-1</max-read-page-messages>
            <max-read-page-bytes>20M</max-read-page-bytes>
            <page-limit-bytes>-1</page-limit-bytes>
            <page-limit-messages>-1</page-limit-messages>
          </address-setting>
        </address-settings>

        <!-- Addresses -->
        <addresses>
          <address name="DLQ">
            <anycast>
              <queue name="DLQ" />
            </anycast>
          </address>
          <address name="ExpiryQueue">
            <anycast>
              <queue name="ExpiryQueue" />
            </anycast>
          </address>
        </addresses>

      </core>
    </configuration>

  bootstrap.xml: |-
    <broker xmlns="http://activemq.apache.org/schema">
      <jaas-security domain="activemq"/>
      <server configuration="file:${artemis.instance}/etc/broker.xml"/>

      <web path="web" rootRedirectLocation="console">
        <binding name="artemis"
                 uri="https://0.0.0.0:${SSL_CONSOLE_PORT}"
                 keyStorePath="${KEYSTORE_LOCATION}"
                 keyStorePassword="${KEYSTORE_PASSWORD}">
          <app name="console" url="console" war="console.war"/>
        </binding>
      </web>
    </broker>
{{- end }}
