kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-pvc
spec:
  accessModes:
    -  {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default .Values.global.rwmStorage }}