apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
type: Opaque
data:
  user: {{ .Values.adminUser.username | b64enc | quote }}
  password: {{ .Values.adminUser.password | b64enc | quote }}
  {{- if or .Values.ssl.enabled (.Values.global.useCertificate | default false) }}
  {{ .Values.ssl.keystorePasswordKey }}: {{ .Values.ssl.keystorePassword | b64enc | quote }}
  {{ .Values.ssl.truststorePasswordKey }}: {{ .Values.ssl.truststorePassword | b64enc | quote }}
  {{- end }}
