apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.broker.type }}
  ports:
  - port: {{ .Values.service.broker.ports.external.openwire | default 61616 }}
    targetPort: {{ .Values.service.broker.ports.internal.openwire | default 61616 }}
    name: openwire
    protocol: TCP
  - port: {{ .Values.service.broker.ports.external.amqp | default 5672 }}
    targetPort: {{ .Values.service.broker.ports.internal.amqp | default 5672 }}
    name: amqp
    protocol: TCP
  {{- if or .Values.ssl.enabled .Values.global.useCertificate }}
  - port: {{ .Values.ssl.acceptorPort | default 61617 }}
    targetPort: {{ .Values.ssl.acceptorPort | default 61617 }}
    name: ssl
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.service.name }}
    release: {{ .Release.Name }}
