apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}-secret
type: Opaque
data:
  tomcatPassword: {{ default "" .Values.tomcat.password | b64enc | quote }}
{{- if .Values.global.internalTlsEnable }}  
  bpsingressPassword: {{ .Values.ingressPassword | b64enc }}
{{- end }}   
