apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-log4j-properties-config
  labels:
    name: {{ .Values.prefix }}-log4j-properties-config
data:
  log4j-properties-config: |-
    #------------------- Log4j2 internals  --------------------------
    #The level of internal Log4j events that should be logged to the console.
    # Valid values for this attribute are "trace", "debug", "info", "warn",
    # "error" and "fatal"
    status = error
    #Either "err" for stderr, "out" for stdout, a file path, or a URL.
    dest = err
    #The name of the configuration.
    name = BPSPropertiesConfig
    monitorInterval = 30
    
    rootLogger.level= WARN
    rootLogger.appenderRefs = A1,F1
    rootLogger.appenderRef.A1.ref = STDOUT
    rootLogger.appenderRef.F1.ref = RollingFile
    
    #------------------- CONSOLE --------------------------
    appender.A1.type = Console
    appender.A1.name = STDOUT
    appender.A1.layout.type = PatternLayout
    appender.A1.layout.pattern = %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.A1.filter.threshold.type = ThresholdFilter
    appender.A1.filter.threshold.level = ERROR
    
    #------------------- FILE --------------------------
    appender.F1.type = RollingFile
    appender.F1.name = RollingFile
    appender.F1.fileName = /opt/tomcat/logs/bps-all.log
    appender.F1.filePattern = /opt/tomcat/logs/bps-all-%d{MM-dd-yy-HH-mm-ss}-%i.log
    appender.F1.layout.type = PatternLayout
    appender.F1.layout.pattern = %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.F1.policies.type = Policies
    appender.F1.policies.size.type = SizeBasedTriggeringPolicy
    appender.F1.policies.size.size = 5MB
    appender.F1.strategy.type = DefaultRolloverStrategy
    appender.F1.strategy.max = 10
    
    #----------------------bps----------------------------
    
    appender.bps.type = RollingFile
    appender.bps.name = bps
    appender.bps.fileName = /opt/tomcat/logs/bps.log
    appender.bps.filePattern = /opt/tomcat/logs/bps-%d{MM-dd-yy-HH-mm-ss}-%i.log
    appender.bps.layout.type = PatternLayout
    appender.bps.layout.pattern= %d{ISO8601} %5p [%t] [%c] - %m%n
    appender.bps.policies.type = Policies
    appender.bps.policies.size.type = SizeBasedTriggeringPolicy
    appender.bps.policies.size.size = 2MB
    appender.bps.strategy.type = DefaultRolloverStrategy
    appender.bps.strategy.max = 10
    
    #-----------------------loggers-------------------------
    logger.bps.name = com.documentum.bps
    logger.bps.level = WARN
    logger.bps.additivity = false
    logger.bps.appenderRef.bps.ref = bps
    
    logger.bpm.name = com.documentum.bpm
    logger.bpm.level = WARN
    logger.bpm.additivity = false
    logger.bpm.appenderRef.bps.ref = bps
