apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
type: Opaque
data:
  activemqUser: {{ default "" .Values.activemq.user_name | b64enc | quote }}
  activemqPassword: {{ default "" .Values.activemq.password | b64enc | quote }}
  globalRegistryPassword: {{ default "" .Values.dfc.globalRegistryPassword | b64enc | quote }}
  docbasePassword: {{ default "" .Values.docbasePassword | b64enc | quote }}
  oAuthClientSecret: {{ default "" .Values.otds.oauth_client_secret | b64enc | quote }}
