# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.actuatorHttpPort }}
    targetPort: {{ .Values.actuatorHttpPort }}
  - name: https
    port: {{ .Values.actuatorHttpsPort }}
    targetPort: {{ .Values.actuatorHttpsPort }}
  selector:
    app: {{ .Values.service.name }}
    name: {{ .Chart.Name }}
    release: {{ .Release.Name }}