########################################################################
# OpenText Intelligent Viewing Kubernetes Secrets
########################################################################

## This is a sample secrets file that could be used if you are creating UPDATE-with-your own kubernetes secret.
## You need to update the "UPDATE-with-your-base64-encoded-password" strings with base64 encoded values.
##   Note that the OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET key needs to be double base64 encoded.
#
## If you are encoding in Linux, make sure you do not include new line characters. For example:
##   echo -n 'aBigLongStringToEncode' | base64
#
## To create this secret in kubernetes, execute the following command (substituting for <namespace> and <existing-secret.yaml>):
##   kubectl -n <namespace> apply -f <example-secret.yaml>

apiVersion: v1
kind: Secret
metadata:
  name: otiv-secrets
type: Opaque
data:
  ## the amqp/rabbitmq password 
  rabbitmq-password: UPDATE-with-your-base64-encoded-password

  ## database admin password 
  OTIV_DB_ADMIN_PASSWORD: &db_password UPDATE-with-your-base64-encoded-password

  ## database iv  password 
  OTIV_DB_PASSWORD: &db_password UPDATE-with-your-base64-encoded-password

  ## OTDS admin password
  ADMIN_USER_PASSWORD: &otds_password UPDATE-with-your-base64-encoded-password

  ## The following OTDS secrets are ONLY required to be defined if otds is enabled within chart ( otds.enabled=true )

  ## OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD is the admin user password for otds;
  ##  no need to explicitly set as it's aliased to the anchor "&otds_password"
  OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD: *otds_password

  ## OTDS_JAKARTA_PERSISTENCE_JDBC_USER is the otds database username
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER: your-base64-encoded-username
    
  ## OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD is the otds database password
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD: UPDATE-with-your-base64-encoded-password

  ## OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET is used for secure synchronized access to backend DB from
  ## frontend instances. The value is a 16 character ASCII string that has been base64 encoded, and
  ## as such must be double base64 encoded here.
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: UPDATE-with-your-double-base64-encoded-16-character-string

  ## The following key is only relevant if the postgresql subchart is enabled, i.e.
  ##   postgresql.enabled=true; no need to explicitly set as it's aliased to anchor "&db_password"
  postgres-password: *db_password

  ## Secret to communicate with the IV Highlight OAuth Client
  OTIV_HIGHLIGHT_CLIENT_SECRET: UPDATE-with-your-base64-encoded-16-character-string

  ## Secret to communicate with the IV Monitoring OAuth Client
  OTIV_MONITOR_CLIENT_SECRET: UPDATE-with-your-base64-encoded-16-character-string

  ## Secret to communicate with the IV Publication OAuth Client
  OTIV_PUBLICATION_CLIENT_SECRET: UPDATE-with-your-base64-encoded-16-character-string

  ## Secret to communicate with the IV Publisher OAuth Client
  OTIV_PUBLISHER_CLIENT_SECRET: UPDATE-with-your-base64-encoded-16-character-string

