

    
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ .Chart.Name }}
   namespace: {{ .Values.namespace  | default .Release.Namespace }}
   labels: 
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec: 
      securityContext:
        fsGroup: {{ .Values.fsGroup }}    
{{- if (empty (.Values.images.pullSecrets | quote) | ternary .Values.global.pullSecretName .Values.images.pullSecrets) }}
      imagePullSecrets:
      - name: {{ .Values.images.pullSecrets | default .Values.global.pullSecretName }}
{{ end }}
      initContainers:
      - name: ccsmartviewextension
        image: {{ .Values.extensionImage.repository | default .Values.global.repository }}/{{ .Values.extensionImage.name }}:{{ .Values.extensionImage.tag }}
        imagePullPolicy: {{ .Values.extensionImage.pullPolicy | default .Values.global.pullPolicyType }}
        command: ['/bin/sh', '-c', '. /opt/ccsmartview/initstartup.sh']
        env:
        - name: CONTEXT
          value: "CCSmartview"
        - name: CLIENTID
          value: {{ .Values.ccsv.clientid |  default .Values.global.msClientId  }}
        - name: HOST
          value: {{ default (include "documentum.publicIngressWithoutProtocol" .)}}/
        - name: WEBAPP_NAME
          value: {{ .Values.env.webappName }}
        - name: APP_NAME
          value: {{ .Values.ccsv.appname }}
        volumeMounts:
          - name: extensionpvc
            mountPath: /opt/ccextension
            subPath: ccsmartview
{{- if .Values.extraInitContainers }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      serviceAccountName: {{ .Values.serviceAccount.serviceAccountName |  default .Values.global.documentumserviceaccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.repository | default .Values.global.repository }}/{{ .Values.images.name | default .Values.global.appserverImageName }}:{{ .Values.images.tag | default .Values.global.appserverImageTag }}
        imagePullPolicy: {{ .Values.images.pullPolicy | default .Values.global.pullPolicyType}}
        {{- if .Values.customConfigurations.custom }}
        command: ['bin/sh', '-c', 'mkdir -p /opt/CC-install;sudo cp -p -Rf /opt/ccextension/ccsmartview/* /opt/CC-install/;sudo chown -Rf 1000:1000 /opt/CC-install/;. /opt/CC-install/extensionstartup.sh']
        {{- else }}
        command: ['bin/sh', '-c', 'mkdir -p /opt/CC-install;cp -p -Rf /opt/ccextension/ccsmartview/* /opt/CC-install/;sudo chown -Rf 1000:1000 /opt/CC-install/;. /opt/CC-install/extensionstartup.sh']
        {{- end }}
        env:
        - name: KUBERNETES
          value: "true"
        - name: CONTAINER_NAME
          value: {{ .Chart.Name | quote }}            
        - name: TOMCAT_SECURE
          value: {{ .Values.tomcat.secure | quote }} 
        - name: TOMCAT_JVM_ARGS
          value: {{ .Values.env.tomcatJVMArgs }} 
        - name: WEBAPP_NAME
          value: {{ .Values.env.webappName }}
        - name: TOMCAT_LOG_FILE_ROTATION
          value: {{ .Values.tomcat.logfilerotation | quote }}
        - name: TOMCAT_LOG_FILE_SIZE
          value: {{ .Values.tomcat.logfilesize | quote }}
        - name: CLIENTID
          value: {{ .Values.ccsv.clientid |  default .Values.global.msClientId  }}
        - name: HOST
          value: {{ default (include "documentum.publicIngressWithoutProtocol" .)}}/       
        - name: APP_NAME
          value: {{ .Values.ccsv.appname }}
        - name: vaultEnabled
          value: {{ .Values.global.isVaultEnabled | quote }}				
          {{- if eq .Values.global.internalTlsEnable true }}          
        - name: tls_enabled
          value: {{ .Values.global.internalTlsEnable | quote }}
          {{- end }}  
        - name: INGRESS_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName | default .Values.global.csSecrets }}
              key: ingress.keystorepassword                
      {{- if .Values.newrelic.enable  |  default .Values.global.newrelic }}
        - name: NEWRELIC_ENABLE
          value: {{ .Values.newrelic.enable |  default .Values.global.newrelic | quote  }}
        - name: NEWRELIC_APP_NAME
          value: {{ .Values.newrelic.app_name }}
        - name: NEWRELIC_PROXY_HOST
          value: {{ .Values.newrelic.proxy_host |  default .Values.global.newrelicProxyHost }}
        - name: NEWRELIC_PROXY_PORT
          value: {{ .Values.newrelic.proxy_port |  default .Values.global.newrelicProxyPort | quote  }}
        - name: NEWRELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.csConfigName |  default .Values.global.csSecrets }}
              key: newrelicLicensekey
      {{- end }}
      {{- if .Values.customConfigurations.custom }}
        - name: CUSTOM_IMPORT
          value: {{ .Values.customConfigurations.custom | quote }}
        - name: LOCALE_NAME
          value: {{ .Values.customConfigurations.locale | quote }}
      {{- end }}      
        ports:
        - containerPort: 8080
          name: clientport 
        volumeMounts:
         {{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
        - mountPath: /opt/dctm/certificate
          name: {{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
          subPath: certificate/{{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
          {{ end }}
        - mountPath: {{ .Values.tomcat.catalinaHome }}/conf/server_configmap.xml
          name: {{ .Chart.Name }}-appserver-server-xml
          subPath: server.xml
        - mountPath: {{ .Values.tomcat.catalinaHome }}/webapps/{{ .Values.env.webappName }}/launcher
          name: {{ .Chart.Name }}-launcher-json
        - mountPath: {{ .Values.tomcat.catalinaHome }}/conf/context.xml
          name: {{ .Chart.Name }}-context-xml
          subPath: context.xml
        - mountPath: /opt/ccextension/
          name: extensionpvc
          subPath: ccsmartview
        {{- if eq .Values.global.isVaultEnabled true }}
        - mountPath: /opt/dctm_docker/vault_config
          name: vault-volume
        - mountPath: /opt/dctm_docker/dsis_binary_volume
          name: dsis-binary-volume
        {{- end }}          

{{- if .Values.customConfigurations.custom }}
        - mountPath: /opt/CC-install/custom
          name: customconfig
{{- end }}
{{ if (eq (empty (.Values.graylog.enable) | ternary .Values.global.grayLogEnable .Values.graylog.enable) false)  }}
        - mountPath: {{ .Values.tomcat.catalinaHome }}/webapps/{{ .Values.env.webappName }}/logs/
          name: shared-logs
          subPath: {{ .Values.env.webappName }}/logs
        - mountPath: {{ .Values.tomcat.catalinaHome }}/logs/
          name: shared-logs
          subPath: logs
{{- end }}
{{ $kubeversion := printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor | replace "+" "" | float64 }}        
        resources:
{{ toYaml .Values.resources | indent 12 }}
        readinessProbe:
          httpGet:
            path: /{{ .Values.env.webappName }}
            port: {{ include "ccsmartview.servicePortNumber" . }}
            {{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
            scheme: HTTPS
            {{- end }}
{{- if ge $kubeversion 1.19 }}
          initialDelaySeconds: {{ default 60 .Values.readinessProbe.initialDelaySeconds }}
{{- else }}
          initialDelaySeconds: {{ default 300 .Values.readinessProbe.initialDelaySeconds }}
{{- end }}
          periodSeconds: 60
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 6
        livenessProbe:
          httpGet:
            path: /{{ .Values.env.webappName }}
            port: {{ include "ccsmartview.servicePortNumber" . }}
            {{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
            scheme: HTTPS
            {{- end }}
{{- if ge $kubeversion 1.19 }}
          initialDelaySeconds: {{ default 60 .Values.livenessProbe.initialDelaySeconds }}
{{- else }}
          initialDelaySeconds: {{ default 300 .Values.livenessProbe.initialDelaySeconds }}
{{- end }}
          periodSeconds: 60
          failureThreshold: 5
{{ if ge $kubeversion 1.19 }}  
        startupProbe:
          httpGet:
            path: /{{ .Values.env.webappName }}
            port: {{ include "ccsmartview.servicePortNumber" . }}
            {{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 60
          periodSeconds: 60
{{- end }}
      volumes:
{{ if (eq (empty (.Values.graylog.enable) | ternary .Values.global.grayLogEnable .Values.graylog.enable) false) }}
        - name: shared-logs
          persistentVolumeClaim:
            claimName: {{ .Values.graylog.pvcName }} 
{{ end }}
{{- if .Values.customConfigurations.custom }}
        - name: customconfig
          emptyDir: {}
{{ end }}
        - name: extensionpvc
          persistentVolumeClaim:
            claimName: {{ .Values.extension.pvcName | default .Values.global.tomcatbase_commonpvcname }} 
        - name: {{ .Chart.Name }}-launcher-json
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-launcher-json         
        - name: {{ .Chart.Name }}-appserver-server-xml
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-server-xml
        - name: {{ .Chart.Name }}-context-xml
          projected:
            sources:
            - configMap:
                name: {{ .Chart.Name }}-context-xml        
          {{- if eq .Values.global.isVaultEnabled true }}  
        - name: dsis-binary-volume
          persistentVolumeClaim:
            claimName: dsis-binary-pvc
        - name: vault-volume
          configMap:
            name: dctm-vault-configmap
          {{- end }}  
                         
       
{{ if (empty (.Values.certificate.use_certificate | quote) | ternary .Values.global.useCertificate .Values.certificate.use_certificate) }}
        - name: {{ .Values.dbrpersistentVolume.dbrdataPVCName | default .Values.global.dbrdataPVCName }}
          persistentVolumeClaim:
            claimName: {{ .Values.certificate.dbrserviceName | default .Values.global.dbrServiceName }}-pvc
{{- end }}
                


