apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-grpc-service
spec:
  selector:
    app: {{ .Values.prefix }}  # match labels in your jar pod
  ports:
    - protocol: TCP
      port: {{ .Values.configMap.extApiconfig.service_port }}       # the port your jar listens on
      targetPort: 9004
