apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-go-service
spec:
  selector:
    app: {{ .Values.prefix }}  # match labels in your jar pod
  ports:
    - protocol: TCP
      port: {{ .Values.configMap.extApiconfig.http_go_server_port }}       # the port your jar listens on
      targetPort: 8888
