{{- if .Values.ssl.enabled }}
apiVersion: v1
data:
  crt: {{ .Values.ssl.crt | b64enc | quote }}
  key: {{ .Values.ssl.key | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.ssl.secret }}
type: Opaque
{{- end }}