apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.resource.name" . }}-configmap
  {{- template "metadata.namespace" . }}
data:
    {{ template "cors.config" . }}
    {{ template "forwarded.config" . }}
    {{- template "markup.secret.keys" . }}
    CORS_ADDITIONAL_HEADERS_LIST: '{{ .Values.global.customHttpHeaders }}'
    COUNTER: '{{ .Values.global.counter }}'
    PITHOS_PROVIDER: {{ .Values.global.database.type }}
    DB_PROVIDER: {{ .Values.global.database.type }}
    DB_HOST: {{ .Values.global.database.hostname }}
    DB_PORT: '{{ .Values.global.database.port }}'
    DB_NAME: {{ .Values.global.database.ivName }}
{{- if (include "is.iv" .) }}
    PITHOS_ADMIN_DB: {{ .Values.global.database.adminDatabase }}
    DB_USER: {{ .Values.global.database.ivUsername }}
    DB_ADMIN_USER: {{ .Values.global.database.adminUsername }}
{{- end }}
    DB_USE_SSL: '{{ .Values.global.database.ssl }}'
    DB_MAX_POOL_SIZE: '{{ .Values.dbMaxPoolSize }}'
{{- if .Values.enableRoleBasedAccessControl }}
    ENABLE_ROLE_BASED_ACCESS_CONTROL: '{{ .Values.enableRoleBasedAccessControl }}'
{{- end }}
    DOC_ROOT: 'https://developer.opentext.com/products_services/aa064dbd-8954-4d0f-8892-65fe2de124bb'
    {{ template "node.forwarding" . }}
{{- if .Values.jwtSecret }}
    MARKUP_JWT_SECRET: '{{ .Values.jwtSecret }}'
{{- end }}
{{- if or .Values.global.enableOtivCustomizedTruststore .Values.global.otivSecretProviderClassCerts.enabled }}
    NODE_EXTRA_CA_CERTS: /opt/certs/combined_crt_file.crt
    DB_SSL_CA_PATH: /opt/certs/combined_crt_file.crt
{{- end }}
    LOG_LEVEL: '{{ .Values.loglevel }}'
    {{- template "new.relic.viewing.config" . }}
    MARKUP_AUTHORITY: {{ $.Values.global.publicWebProtocol }}://{{ include "ingress.fqdn.markup" .}}
    NODE_ENV: production
{{- if .Values.nodeOptions }}
    NODE_OPTIONS: '{{ .Values.nodeOptions }}'
{{- end }}
    OTDS_CERT_UPDATE_INTERVAL: '{{ .Values.global.otdsCertUpdateInterval }}'
    PORT: '{{ .Values.service.targetPort }}'
{{- if not (include "is.iv" .) }}
    SUBSCRIPTION_DELETE_INTERVAL: '10'
    SUBSCRIPTION_DELETE_LIMIT: '10000'
{{- end }}
    {{- template "timezone" . }}
    VERTX_CLUSTER_NETWORK_PORT: '{{ .Values.global.hazelport }}'
    __VERSION__: '{{ template "version.stamp" . }}'
