apiVersion: v1
kind: ConfigMap
metadata:
  name: jupiter-configmap
  
data:
  {{- if or .Values.ssl.enabled .Values.global.useCertificate }}
  jupiter.server.url: https://{{ .Values.service.name }}:{{ .Values.service.targetPort }}
  jupiter.server.url.check: https://{{ .Values.service.name }}:{{ .Values.service.targetPort }}/health/ready
  {{- else }}
  jupiter.server.url: http://{{ .Values.service.name }}:{{ .Values.service.targetPort }}
  jupiter.server.url.check: http://{{ .Values.service.name }}:{{ .Values.service.targetPort }}/health/ready
  {{- end }}