# Default values for publication.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

# when pod termination is initiated, amount of time k8s waits before forcibly killing the pod
terminationGracePeriodSeconds:

## hpa enabled at the global level
hpa:
  replicas:
    min: 1
    max: 3
  # the use of the targert type; valid values are utilization or averageValue
  #  defaults to global.hpa.targetType if not set
  targetType:
  # indicate whehter the cpu and memory targets are set. If not set, the global.hpa proerty values are used
  cpuTargetEnabled:
  memoryTargetEnabled:

  # values used if targetType set to utilization
  utilization:
    cpu: 70
    memory: 70
  # values used if targetType set to averageValue
  averageValue:
    cpu: 400m
    memory: 1Gi
  scaleDown:
    periodSeconds: 120
    stabilizationWindowSeconds: 300
  scaleUp:
    periodSeconds: 60
    stabilizationWindowSeconds: 300

image:
  name: otiv-asset

# potential loglevel values: ERROR, WARN, INFO, DEBUG, TRACE
loglevel:
  example: DEBUG
  #artifacts: DEBUG
  #hazelCast: DEBUG
  #netty: DEBUG
  #system: DEBUG
  #vertx: DEBUG
  #vertxWebHandler: DEBUG

service:
  type: ClusterIP
  albType: NodePort
  port: 80
  targetPort: 9093
  # adds listed annotations to all otiv services
  # each entry needs to be a single string that contains a colon ( : ) that separates
  #   the property name and value
  annotations: []

resources:
  enabled: false
  requests:
    cpu: 250m
    memory: 0.6Gi
  limits:
    cpu: 500m
    memory: 1.2Gi


livenessProbe:
  enabled: true
  initialDelaySeconds: 100
  initialDelaySecondsCS: 1800
  timeoutSeconds: 3
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 25
  failureThreshold: 2

## Available as of kubernetes version 1.16
startupProbe:
  enabled: true
  initialDelaySeconds: 35
  timeoutSeconds: 2
  periodSeconds: 30
  failureThreshold: 10
  failureThresholdCS: 80

ingress:
  enabled: true

auth:
    resource: false
    #identityHeaders:

publication:
  port: 80


# If set to true, Forwarded/X-Forwarded-Host header whitelist enforcement is enabled
#   and the services validate that the Forwarded/X-Forwarded-* headers adhere to what's 
#   allowed by the forwardedHostsList or forwardedHostsRegex properties.
#
# If set to true and the forwardedHostsList and forwardedHostsRegex are not defined 
#    or have been defined with an invalid syntax, the services will fail to start.
# If both of these properties are configured, forwardedHostsRegex takes precedence.
# The Forwarded/X-Forwarded-Host headers in incoming requests that do not match the
#    properties whitelist criteria are ignroed.
# If not defined here, corresponding global property values are used
#enforceForwardedHosts: false

# a comma seperated list of FQDNs (cannot specify protocols such as https) that are used
#   for validating the Forwarded/X-Forwarded-* headers.
#forwardedHostsList:

# a regex pattern to match FQDNs
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character, e.g.: .*site.sample.*
#forwardedHostsRegex:

# if set to true, requests will be only be accepted from the servers listed in corsOriginsList
#  or corsOriginsRegex; if both are defined, corsOriginRegex has precedence
# If not defined here, corresponding global property values are used
#enforceCorsOrigins: false

# a comma seperated list of servers that OTIV services will allow origin requests from
# each origin should start with https:// or http://
#corsOriginsList:

# a regex pattern for servers that OTIV services will allow origin requests from
# The metacharacter * is a modifier and matches the preceeding character 0 or more times;
#  so * needs to be after another character; typically this will be the metacharacter . (dot)
#  which represents any single character. An example value would be: .*site.sample.*
#corsOriginsRegex:
