{{- if eq .Values.ingress.enable true }}
#Ingress Object
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}  
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | indent 4 | trim }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.ingressHostName }}.{{ .Values.ingress.clusterDomainName | default .Values.global.ingressDomain}}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port}}
        path: {{ .Values.ingress.path }}
{{- end }}