{{- if .Values.persistentVolume.awsEFS }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.existVolumePv }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.awsEFSCSIClaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClass | default .Values.global.rwmStorage }}
  csi:
    driver: {{ .Values.persistentVolume.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.persistentVolume.awsEFSCSIHandle }}
{{- end }}