apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-appserver-xml
data:
{{- if (eq .Values.global.internalTlsEnable true) }}
  cs_configmap_server.xml: |-
   <?xml version="1.0" encoding="UTF-8" standalone="no"?>
   <!--
     Licensed to the Apache Software Foundation (ASF) under one or more
     contributor license agreements.  See the NOTICE file distributed with
     this work for additional information regarding copyright ownership.
     The ASF licenses this file to You under the Apache License, Version 2.0
     (the "License"); you may not use this file except in compliance with
     the License.  You may obtain a copy of the License at
   
         http://www.apache.org/licenses/LICENSE-2.0
   
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
   --><!-- Note:  A "Server" is not itself a "Container", so you may not
        define subcomponents such as "Valves" at this level.
        Documentation at /docs/config/server.html
    --><Server port="9089" shutdown="DCTM_SHUTDOWN_COMMAND">
   
       <Listener className="org.apache.catalina.startup.VersionLoggerListener"/>
   
       <!-- Security listener. Documentation at /docs/config/listeners.html
     <Listener className="org.apache.catalina.security.SecurityListener" />
     -->
   
       <!-- OpenSSL support using Tomcat Native -->
   
       <Listener className="org.apache.catalina.core.AprLifecycleListener"/>
   
       <!-- OpenSSL support using FFM API from Java 22 -->
   
       <!-- <Listener className="org.apache.catalina.core.OpenSSLLifecycleListener" /> -->
   
       <!-- Prevent memory leaks due to use of particular java/javax APIs-->
   
       <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
   
       <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
   
       <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
   
       <!-- Global JNDI resources
          Documentation at /docs/jndi-resources-howto.html
     -->
   
       <GlobalNamingResources>
   
           <!-- Editable user database that can also be used by
            UserDatabaseRealm to authenticate users
       -->
   
           <Resource auth="Container" description="User database that can be updated and saved" factory="org.apache.catalina.users.MemoryUserDatabaseFactory" name="UserDatabase" pathname="conf/tomcat-users.xml" type="org.apache.catalina.UserDatabase"/>
   
           <Resource auth="Container" brokerName="ActiveMQBroker" brokerURL="tcp://dcs-pg-0:9084" description="JMS Connection Factory" factory="org.apache.activemq.jndi.JNDIReferenceFactory" name="jms/TouchRpcQueueConnectionFactory" type="org.apache.activemq.ActiveMQConnectionFactory" useEmbeddedBroker="false"/>
           <Resource auth="Container" factory="org.apache.activemq.jndi.JNDIReferenceFactory" name="jms/queue/touchRpcQueue" physicalName="touchRpcQueue" type="org.apache.activemq.command.ActiveMQQueue"/>
       </GlobalNamingResources>
   
       <!-- A "Service" is a collection of one or more "Connectors" that share
          a single "Container" Note:  A "Service" is not itself a "Container",
          so you may not define subcomponents such as "Valves" at this level.
          Documentation at /docs/config/service.html
      -->
   
       <Service name="Catalina">
   
           <!--The connectors can use a shared executor, you can define one or more named thread pools-->
   
           <!--
       <Executor name="tomcatThreadPool" namePrefix="catalina-exec-"
           maxThreads="{{ default .Values.global.tomcatMaxThreads .Values.tomcat.maxThreads }}" minSpareThreads="4"/>
       -->
   
           <!-- A "Connector" represents an endpoint by which requests are received
            and responses are returned. Documentation at :
            HTTP Connector: /docs/config/http.html
            AJP  Connector: /docs/config/ajp.html
            Define a non-SSL/TLS HTTP/1.1 Connector on port 8080
       -->
   
       <Connector port="9082"
                  protocol="org.apache.coyote.http11.Http11NioProtocol"
                  maxThreads="{{ default .Values.global.tomcatMaxThreads .Values.tomcat.maxThreads }}"
                  scheme="https"
                  SSLEnabled="true"
                  secure="true">
           <SSLHostConfig ciphers="TLS_AES_256_GCM_SHA384">
               <Certificate certificateKeystoreFile="/opt/dctm/certificate/ingress.p12"
                            certificateKeystorePassword="INGRESS_KEYSTOREPASSWORD"/>
           </SSLHostConfig>
       </Connector>

   
           <!-- A "Connector" using the shared thread pool-->
   
           <!--
       <Connector executor="tomcatThreadPool"
                  port="8080" protocol="HTTP/1.1"
                  connectionTimeout="{{ default .Values.global.tomcatConnectionTimeout .Values.tomcat.connectionTimeout }}"
                  redirectPort="8443"
                  maxParameterCount="1000"
                  />
       -->
   
           <!-- Define an SSL/TLS HTTP/1.1 Connector on port 8443 with HTTP/2
            This connector uses the NIO implementation. The default
            SSLImplementation will depend on the presence of the APR/native
            library and the useOpenSSL attribute of the AprLifecycleListener.
            Either JSSE or OpenSSL style configuration may be used regardless of
            the SSLImplementation selected. JSSE style configuration is used below.
       -->
   
           <!--
       <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
                  maxThreads="{{ default .Values.global.tomcatMaxThreads .Values.tomcat.maxThreads }}" SSLEnabled="true"
                  maxParameterCount="1000"
                  >
           <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
           <SSLHostConfig>
               <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                            certificateKeystorePassword="changeit" type="RSA" />
           </SSLHostConfig>
       </Connector>
       -->
   
           <!-- Define an AJP 1.3 Connector on port 8009 -->
   
           <!--
       <Connector protocol="AJP/1.3"
                  address="::1"
                  port="8009"
                  redirectPort="8443"
                  maxParameterCount="1000"
                  />
       -->
   
           <!-- An Engine represents the entry point (within Catalina) that processes
            every request.  The Engine implementation for Tomcat stand alone
            analyzes the HTTP headers included with the request, and passes them
            on to the appropriate Host (virtual host).
            Documentation at /docs/config/engine.html -->
   
           <!-- You should set jvmRoute to support load-balancing via AJP ie :
       <Engine name="Catalina" defaultHost="localhost" jvmRoute="jvm1">
       -->
   
           <Engine defaultHost="localhost" name="Catalina">
   
               <!--For clustering, please take a look at documentation at:
             /docs/cluster-howto.html  (simple how to)
             /docs/config/cluster.html (reference documentation) -->
   
               <!--
         <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>
         -->
   
               <!-- Use the LockOutRealm to prevent attempts to guess user passwords
              via a brute-force attack -->
   
               <Realm className="org.apache.catalina.realm.LockOutRealm">
   
                   <!-- This Realm uses the UserDatabase configured in the global JNDI
                resources under the key "UserDatabase".  Any edits
                that are performed against this UserDatabase are immediately
                available for use by the Realm.  -->
   
                   <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
   
               </Realm>
   
               <Host appBase="webapps" autoDeploy="true" name="localhost" unpackWARs="true">
   
                   <!-- SingleSignOn valve, share authentication between web applications
                Documentation at: /docs/config/valve.html -->
   
                   <!--
           <Valve className="org.apache.catalina.authenticator.SingleSignOn" />
           -->
   
                   <!-- Access log processes all example.
                Documentation at: /docs/config/valve.html
                Note: The pattern used is equivalent to using pattern="common" -->
   
                   <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" pattern="%h %l %u %t &quot;%r&quot; %s %b" prefix="localhost_access_log" suffix=".txt"/>
   
                   <Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false"/>
   
               </Host>
           </Engine>
       </Service>
   </Server>
{{ else }}
  cs_configmap_server.xml: |-
   <?xml version="1.0" encoding="UTF-8" standalone="no"?>
   <!--
     Licensed to the Apache Software Foundation (ASF) under one or more
     contributor license agreements.  See the NOTICE file distributed with
     this work for additional information regarding copyright ownership.
     The ASF licenses this file to You under the Apache License, Version 2.0
     (the "License"); you may not use this file except in compliance with
     the License.  You may obtain a copy of the License at
   
         http://www.apache.org/licenses/LICENSE-2.0
   
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
   --><!-- Note:  A "Server" is not itself a "Container", so you may not
        define subcomponents such as "Valves" at this level.
        Documentation at /docs/config/server.html
    --><Server port="9089" shutdown="DCTM_SHUTDOWN_COMMAND">
   
       <Listener className="org.apache.catalina.startup.VersionLoggerListener"/>
   
       <!-- Security listener. Documentation at /docs/config/listeners.html
     <Listener className="org.apache.catalina.security.SecurityListener" />
     -->
   
       <!-- OpenSSL support using Tomcat Native -->
   
       <Listener className="org.apache.catalina.core.AprLifecycleListener"/>
   
       <!-- OpenSSL support using FFM API from Java 22 -->
   
       <!-- <Listener className="org.apache.catalina.core.OpenSSLLifecycleListener" /> -->
   
       <!-- Prevent memory leaks due to use of particular java/javax APIs-->
   
       <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
   
       <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
   
       <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
   
       <!-- Global JNDI resources
          Documentation at /docs/jndi-resources-howto.html
     -->
   
       <GlobalNamingResources>
   
           <!-- Editable user database that can also be used by
            UserDatabaseRealm to authenticate users
       -->
   
           <Resource auth="Container" description="User database that can be updated and saved" factory="org.apache.catalina.users.MemoryUserDatabaseFactory" name="UserDatabase" pathname="conf/tomcat-users.xml" type="org.apache.catalina.UserDatabase"/>
   
           <Resource auth="Container" brokerName="ActiveMQBroker" brokerURL="tcp://dcs-pg-0:9084" description="JMS Connection Factory" factory="org.apache.activemq.jndi.JNDIReferenceFactory" name="jms/TouchRpcQueueConnectionFactory" type="org.apache.activemq.ActiveMQConnectionFactory" useEmbeddedBroker="false"/>
           <Resource auth="Container" factory="org.apache.activemq.jndi.JNDIReferenceFactory" name="jms/queue/touchRpcQueue" physicalName="touchRpcQueue" type="org.apache.activemq.command.ActiveMQQueue"/>
       </GlobalNamingResources>
   
       <!-- A "Service" is a collection of one or more "Connectors" that share
          a single "Container" Note:  A "Service" is not itself a "Container",
          so you may not define subcomponents such as "Valves" at this level.
          Documentation at /docs/config/service.html
      -->
   
       <Service name="Catalina">
   
           <!--The connectors can use a shared executor, you can define one or more named thread pools-->
   
           <!--
       <Executor name="tomcatThreadPool" namePrefix="catalina-exec-"
           maxThreads="{{ default .Values.global.tomcatMaxThreads .Values.tomcat.maxThreads }}" minSpareThreads="4"/>
       -->
   
           <!-- A "Connector" represents an endpoint by which requests are received
            and responses are returned. Documentation at :
            HTTP Connector: /docs/config/http.html
            AJP  Connector: /docs/config/ajp.html
            Define a non-SSL/TLS HTTP/1.1 Connector on port 8080
       -->
   
           <Connector Server=" " connectionTimeout="{{ default .Values.global.tomcatConnectionTimeout .Values.tomcat.connectionTimeout }}" maxParameterCount="1000" port="9080" protocol="HTTP/1.1" redirectPort="8443"/>
   
           <!-- A "Connector" using the shared thread pool-->
   
           <!--
       <Connector executor="tomcatThreadPool"
                  port="8080" protocol="HTTP/1.1"
                  connectionTimeout="{{ default .Values.global.tomcatConnectionTimeout .Values.tomcat.connectionTimeout }}"
                  redirectPort="8443"
                  maxParameterCount="1000"
                  />
       -->
   
           <!-- Define an SSL/TLS HTTP/1.1 Connector on port 8443 with HTTP/2
            This connector uses the NIO implementation. The default
            SSLImplementation will depend on the presence of the APR/native
            library and the useOpenSSL attribute of the AprLifecycleListener.
            Either JSSE or OpenSSL style configuration may be used regardless of
            the SSLImplementation selected. JSSE style configuration is used below.
       -->
   
           <!--
       <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
                  maxThreads="{{ default .Values.global.tomcatMaxThreads .Values.tomcat.maxThreads }}" SSLEnabled="true"
                  maxParameterCount="1000"
                  >
           <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
           <SSLHostConfig>
               <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                            certificateKeystorePassword="changeit" type="RSA" />
           </SSLHostConfig>
       </Connector>
       -->
   
           <!-- Define an AJP 1.3 Connector on port 8009 -->
   
           <!--
       <Connector protocol="AJP/1.3"
                  address="::1"
                  port="8009"
                  redirectPort="8443"
                  maxParameterCount="1000"
                  />
       -->
   
           <!-- An Engine represents the entry point (within Catalina) that processes
            every request.  The Engine implementation for Tomcat stand alone
            analyzes the HTTP headers included with the request, and passes them
            on to the appropriate Host (virtual host).
            Documentation at /docs/config/engine.html -->
   
           <!-- You should set jvmRoute to support load-balancing via AJP ie :
       <Engine name="Catalina" defaultHost="localhost" jvmRoute="jvm1">
       -->
   
           <Engine defaultHost="localhost" name="Catalina">
   
               <!--For clustering, please take a look at documentation at:
             /docs/cluster-howto.html  (simple how to)
             /docs/config/cluster.html (reference documentation) -->
   
               <!--
         <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>
         -->
   
               <!-- Use the LockOutRealm to prevent attempts to guess user passwords
              via a brute-force attack -->
   
               <Realm className="org.apache.catalina.realm.LockOutRealm">
   
                   <!-- This Realm uses the UserDatabase configured in the global JNDI
                resources under the key "UserDatabase".  Any edits
                that are performed against this UserDatabase are immediately
                available for use by the Realm.  -->
   
                   <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
   
               </Realm>
   
               <Host appBase="webapps" autoDeploy="true" name="localhost" unpackWARs="true">
   
                   <!-- SingleSignOn valve, share authentication between web applications
                Documentation at: /docs/config/valve.html -->
   
                   <!--
           <Valve className="org.apache.catalina.authenticator.SingleSignOn" />
           -->
   
                   <!-- Access log processes all example.
                Documentation at: /docs/config/valve.html
                Note: The pattern used is equivalent to using pattern="common" -->
   
                   <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" pattern="%h %l %u %t &quot;%r&quot; %s %b" prefix="localhost_access_log" suffix=".txt"/>
   
                   <Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false"/>
   
               </Host>
           </Engine>
       </Service>
   </Server>
{{- end }}