#Servics
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  ports:
  - port: {{ .Values.ports.docbaseport }}
    name: docbaseport
  - port: {{ .Values.ports.docbasesslport }}
    name: docbasesslport              
  clusterIP: None
  selector:
    app: {{ .Values.serviceName }}
---
#JMS Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-jms-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.jmsport }}
  selector:
    app: {{ .Values.serviceName }}
---
#TNS Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-tns-service
spec:
  type: ClusterIP
  ports:
    - port: {{ eq .Values.global.internalTlsEnable true | ternary .Values.ports.tnssslport .Values.ports.tnsport }}
  selector:
    app: {{ .Values.serviceName }}