{{ if eq .Values.platform "aws" }}
{{ if eq .Values.ExtCS.useELB true }}
{{ if (empty (.Values.ExtCS.enable | quote) | ternary .Values.global.externalAccessEnabled .Values.ExtCS.enable) }}
{{ if eq .Values.ExtCS.createExtService true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}        
  name: csext-{{ .Values.serviceName }}
{{ if eq .Values.ExtCS.useLBAnnotations true }}
  annotations:
    {{ toJson .Values.ExtCS.LBAnnotations }}
{{ end }}    
spec:    
  ports:
  - name: csnative
    port: 80
    protocol: TCP
    targetPort: {{ .Values.ports.docbaseport }}
  - name: csssl    
    port: 81
    protocol: TCP
    targetPort: {{ .Values.ports.docbasesslport }}
  selector:
    app: {{ .Values.serviceName }}
  sessionAffinity: None
  type: LoadBalancer
{{ end }}
{{ end }}
{{ end }}
{{ end }}