apiVersion: v1
appVersion: "25.4"
description: A Helm chart installing DCTM Content Ingestion Service
maintainers:
- email: pgopalan@opentext.com
  name: Pradeep Gopalan
name: dctm-dcis
version: "25.4"
