  # This secret is used for CC, DB

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: {{ .Values.secret.type }}
data:
  DB_PASSWORD:  {{ default "" .Values.secret.DB_PASSWORD | b64enc | quote }}
  DB_SSLCERT: {{ default ""  .Values.configmap.DB_SSL_CA | b64enc }}  