# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.indexserver.name }}
{{- with .Values.indexServerServiceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}  
spec:
  clusterIP: None
  ports:
  - name: is-port
    port: {{ .Values.service.indexserver.port }}
    targetPort: {{ .Values.service.indexserver.targetPort }}
    protocol: TCP
  selector:
    xplore/app: {{ .Values.service.indexserver.name }}
    xplore/name: {{ .Chart.Name }}
    xplore/release: {{ .Release.Name }}  
