{{- if .Values.global.dctmclientinstaller.enabled }}
{{- if .Values.bravatls.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-brava-certs
type: Opaque
data:
{{ (.Files.Glob "certificates/*").AsSecrets | indent 2 }}
{{end}}
{{- end }}
