{{- if .Values.global.dctmclientinstaller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: d2classic-log4j2-properties
  {{- template "configMap.labels" . }}
data:
  log4j2.properties: |-
    name=PropertiesConfig
    #log-dir location should be changed to application log directory
    property.log-dir ={{ .Values.log4j.file | toString | replace "[" "" | replace "]" "" | replace "/ " "/" | replace " /" "/" }}

    rootLogger.level={{ .Values.log4j.logLevel }}
    rootLogger.appenderRefs=A1, F1
    rootLogger.appenderRef.A1.ref=STDOUT
    rootLogger.appenderRef.F1.ref=File
    monitorInterval=60

    #------------------- CONSOLE --------------------------
    appender.A1.type=Console
    appender.A1.name=STDOUT
    appender.A1.layout.type=PatternLayout
    appender.A1.layout.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%t] %c: %m%n
    appender.A1.filter.threshold.type=ThresholdFilter
    appender.A1.filter.threshold.level=ERROR

    #------------------- FILE --------------------------
    appender.F1.type=RollingFile
    appender.F1.name=File
    appender.F1.fileName=${log-dir}/D2-log4j.log
    appender.F1.filePattern=${log-dir}/D2-log4j-%d{yyyy-MM-dd}.log
    appender.F1.layout.type=PatternLayout
    appender.F1.layout.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%t] %c: %m%n
    appender.F1.policies.type=Policies
    appender.F1.policies.time.type=TimeBasedTriggeringPolicy
    appender.F1.policies.time.interval=1
    appender.F1.policies.time.modulate=true
    appender.F1.policies.size.type=SizeBasedTriggeringPolicy
    appender.F1.policies.size.size=100MB
    appender.F1.strategy.type=DefaultRolloverStrategy
    appender.F1.strategy.max=3
    {{- if $configFileAppendsValues := .Values.log4j.log4j2_properties  }}
    {{ $configFileAppendsValues | nindent 4 }}
    {{- end }}

{{- $configFileOverridesFile := printf "%s/%s" .Values.configFileOverrideFilesDir "log4j2.properties" }}
{{- $configFileMsg0 := printf "\n\n##### Begin lines added from %s\n" $configFileOverridesFile }}
{{- $configFileMsg1 := printf "##### End lines added from %s" $configFileOverridesFile }}
{{- $configFileLinesToAppend := .Files.Get $configFileOverridesFile }}
{{- if $configFileLinesToAppend }}
{{ $configFileMsg0 | indent 4 }}
{{ $configFileLinesToAppend | indent 4 }}
{{ $configFileMsg1 | indent 4 }}
{{- end }}

    {{- end }}
