apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.userName }}-web-xml
  {{- template "configMap.labels" . }}
data:
  web.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <web-app xmlns="http://java.sun.com/xml/ns/javaee"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
              http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
              version="3.0" >
        <display-name>Sftp User Management</display-name>
        <servlet>
                <servlet-name>ServerCheck</servlet-name>
                <display-name>ServerCheck</display-name>
                <description></description>
                <servlet-class>com.documentum.sftpusersmanagement.servlets.ServerCheck</servlet-class>
        </servlet>
        <servlet-mapping>
                <servlet-name>ServerCheck</servlet-name>
                <url-pattern>/servercheck</url-pattern>
        </servlet-mapping>
        <error-page>
            <error-code>404</error-code>
            <location>/errors/redirect/404</location>
        </error-page>
        <error-page>
            <error-code>500</error-code>
            <location>/errors/redirect/500</location>
        </error-page>
    {{- if $configFileAppendsValues := .Values.web_xml }}
    {{ $configFileAppendsValues | nindent 4 }}
    {{- end }}
    </web-app>