apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.thumbnailserver_configMap_name }}  
data:
  log4j: |
    rootLogger.level=WARN
    rootLogger.appenderRefs=A1, F1
    rootLogger.appenderRef.A1.ref=STDOUT
    rootLogger.appenderRef.F1.ref=File
    monitorInterval=60
    property.filename=/opt/dctm

    #------------------- CONSOLE --------------------------
    appender.A1.type=Console
    appender.A1.name=STDOUT
    appender.A1.layout.type=PatternLayout
    appender.A1.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.A1.filter.threshold.type=ThresholdFilter
    appender.A1.filter.threshold.level=ERROR

    #------------------- FILE --------------------------
    appender.F1.type=RollingFile
    appender.F1.name=File
    appender.F1.fileName=${filename}/logs/log4j.log
    appender.F1.filePattern=${filename}/logs/log4j.log.%d{yyyy-MM-dd}
    appender.F1.layout.type=PatternLayout
    appender.F1.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.F1.policies.type=Policies
    appender.F1.policies.time.type=TimeBasedTriggeringPolicy
    appender.F1.policies.time.interval=1
    appender.F1.policies.time.modulate=true
    appender.F1.policies.size.type=SizeBasedTriggeringPolicy
    appender.F1.policies.size.size=10MB
    appender.F1.strategy.type=DefaultRolloverStrategy
    appender.F1.strategy.max=5

    #------------------- CATEGORY TRACE FILE --------------------------

    appender.FILE_TRACE.type=RollingFile
    appender.FILE_TRACE.name=FileTrace
    appender.FILE_TRACE.fileName=${filename}/logs/trace.log
    appender.FILE_TRACE.filePattern=${filename}/logs/trace.log.%d{yyyy-MM-dd}
    appender.FILE_TRACE.layout.type=PatternLayout
    appender.FILE_TRACE.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.FILE_TRACE.policies.type=Policies
    appender.FILE_TRACE.policies.time.type=TimeBasedTriggeringPolicy
    appender.FILE_TRACE.policies.time.interval=1
    appender.FILE_TRACE.policies.time.modulate=true
    appender.FILE_TRACE.policies.size.type=SizeBasedTriggeringPolicy
    appender.FILE_TRACE.policies.size.size=100MB
    appender.FILE_TRACE.strategy.type=DefaultRolloverStrategy
    appender.FILE_TRACE.strategy.max=5

    logger.FILE_TRACE.name=trace
    logger.FILE_TRACE.level=debug
    logger.FILE_TRACE.additivity=false
    logger.FILE_TRACE.appenderRef.FILE_TRACE.ref=FileTrace