{{- if not .Values.justDatabase }}
{{- if not .Values.global.otdsMigration }}
{{- if (include "includeCommonTemplates" .) }}
apiVersion: v1
kind: Service
metadata:
  name: cvt-hazel
  {{- template "metadata.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "brava.name" . }}
    app.kubernetes.io/instance: hazel-otiv-svc
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.global.hazelport }}
      protocol: TCP
      {{- if (include "supportsAppProtocol" .) }}
      appProtocol: tcp
      {{- end }}
      name: hazelcast
  selector:
      hazelcast: cvt
      {{- template "hazelcast.namespace" . }}
{{- end }}
{{- end }}
{{- end }}
