{{- if hasKey .Values.pvc "createPV" }}
{{- if and  (eq .Values.pvc.enablePV true) (eq .Values.pvc.createPV true) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.consul.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
---
{{ if eq .Values.metadata.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.metadata.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
{{ end }}
---
{{ if eq .Values.syncagent.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.syncagent.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
{{ end }}
---
{{ if eq .Values.syncnshareManual.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.syncnshareManual.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
{{ end }}
---
{{ if eq .Values.coreNotification.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.coreNotification.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
{{ end }}
---
{{ if eq .Values.mailService.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prefix | default .Values.global.dccPrefix }}-{{ .Values.mailService.prefix }}-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClass }}
  csi:
    driver: {{ .Values.pvc.awsEFSCSIDriver }}
    volumeHandle: {{ .Values.pvc.awsEFSCSIHandle }}
{{ end }}
{{- end }}
{{- end }}