# These are samples of everything that can be bootstrapped
# Keep and customize only the data you wish to boostrap and delete everything else

systemAttributes:
  - name: otdsautoconfig.test.1
    value: test1

# Global password policy. Can also be set per partition.
passwordPolicy:
  passwordHistoryMaximumCount: 3
  daysBeforeNewPasswordMayBeChanged: 1
  passwordMaximumDuration: 90
  lockoutFailureCount: 3
  lockoutDuration: 15
  minimumNumberOfCharacters: 8
  complexPasswordValidationEnabled: true
  minimumNumberOfDigits: 1
  minimumNumberOfSymbols: 1
  minimumNumberOfUppercase: 1
  minimumNumberOfLowercase: 1
  minimumChangesToPreviousPassword: 0
  maxNumberOfConsecutiveANCharsInPassword: 0
  blockCommonPassword: false

# Global two factor auth settings. Can also be set per partition.
twoFactorSettings:
  inheritSettings: false
  enabled: false
  applyToSSOUsers: false
  applyToExtranetOnly: false
  allowRememberedDevices: false
  requireClientCertificate: false

trustedSites:
  - https://autoConfiguredSite2/mypath

#Disable the http.negotiate auth handler
authHandlers:
  - _name: http.negotiate
    _id: http.negotiate
    _description: Handles "Negotiate" authentication with the browser.
    _class: com.opentext.otds.as.drivers.http.NegotiateHttpAuthenticationHandler
    _enabled: false
    _priority: 20
    _scope:
    _properties:
      - _key: com.opentext.otds.as.drivers.http.negotiate.enablemobile
        _value: 'false'
    _authPrincipalAttrNames:
      - oTExternalID4

partitions:
  - name: autoConfigPartition
    adminUsers:
      - myUser@somePartition
    adminGroups:
      - myGroup@somePartition
    adminRoles: 
      - myRole@somePartition
    passwordPolicy:
      #see global policy for properties
    twoFactorSettings:
      #see global policy for properties
    restrictions:
      usersLimit: -1
      groupsLimit: -1
      bindAuthToAllowedDomains: false
      restrictProvToAllowedDomains: false
      allowedDomains:
       - domain1
       - domain2
      allowedAuthIPs:
       - '10.1.1.1'
       - '10.0.0.0/8'

# Note: To configure twoFactorSettings,restrictions,admins on a synchronized partition
# add an entry under 'partitions' with the same partition name as the synchronized partition
syncPartitions:
  - profileName: autoCfgSyncPartition
    description: auto config sync partition description
    baseDN: <appropriate baseDN>
    #...
    # The required properties for a sync partition is extensive.
    # Please consult the documentation in Swagger for /identityproviderprofiles
    # along with the content sent by the OTDS administration UI
    # when creating a synchronized partition.
    #

oauthClients:
  - name: autoConfigClient1
    secret: eecec09ebfb5196bb1dd
    confidential: true

users:
  - name: autoConfigUser1
    userPartitionID: autoConfigPartition
    values: 
     - name: userPassword
       values: 
         - Password@123

groups:
  - name: autoConfigGroup1
    userPartitionID: autoConfigPartition
    users: 
     - autoConfigUser1@autoConfigPartition
    groups: 
     - autoConfigGroup2@autoConfigPartition
  - name: autoConfigGroup2
    userPartitionID: autoConfigPartition

roles:
  - name: autoConfigRole1
    userPartitionID: autoConfigPartition
    users:
     - autoConfigUser1@autoConfigPartition
    groups:
     - autoConfigGroup1@autoConfigPartition

resources:
  - resourceName: autoConfigResource1
    description: auto-configured resource 1
    logoutURL: http://mylogouturl
    logoutMethod: GET
    userAttributeMapping:
     - sourceAttr:
        - oTExternalID3
       destAttr: __NAME__
       mappingFormat: "%s"
    groupAttributeMapping:
     - sourceAttr:
        - cn
       destAttr: __NAME__
       mappingFormat: "%s"

accessRoles:
  - name: autoConfigAccessRole
    accessRoleMembers:
      userPartitions:
       - userPartition: autoConfigPartition
      users:
       - name: autoConfigUser1
         userPartition: autoConfigPartition
      groups:
       - name: autoConfigGroup1
         userPartition: autoConfigPartition
      roles:
       - name: autoConfigRole1
         userPartition: autoConfigPartition
    resources:
      - resourceName: autoConfigResource1

licenses:
  - name: my-test-license
    description: License for testing XYZ
    values:
    - name: oTLicenseFile
      values: |-
        [PRODUCT]
        LicenseIssuer=OpenText Corp
        ... chopped for brevity...
        Pubkey:ABC
        Signature:ABC
    - name: oTLicenseResourceName
      values: autoConfigResource1

smtpConfig:
  host: smtphost
  port: 25
  useSSL: false
  timeout: 0
  from: otds@domain.com
  fromName:
  
notifConfig:
  frequency: 30
  maxRetries: 5
  eventIDs:
    - ACCOUNT_LOCKED
  eventLevels:
    - INFO
  otdsNotificationsEnabled: false
  defaultLanguage: English
  spsNotificationsEnabled: false
  spsCertificatesNotificationsThreshold: 14
  spsSendSchedule: 24
  passwordNotificationsEnabled: false
  otdsEmailAddresses:
    - user@domain.com

auditConfig:
  enabled: false
  daysToKeep: '90'
  auditTo: DATABASE
  eventIDs:
   - USER_CREATE
   - USER_DELETE
   - USER_AUTH_FAILED
   - GROUP_CREATE
   - GROUP_DELETE
