{{- if .Values.serviceAccount.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.serviceAccountName | default .Values.global.documentumserviceaccount}}
{{- end }}