# This secret is created to handle applications expecting single encoding of the tlscert and tlskey.
{{- if (eq .Values.global.internalTlsEnable true) }}
apiVersion: v1
kind: Secret
metadata:
  name: otds-secret-tls 
type: kubernetes.io/tls
data:
  tls.crt: {{ default "" .Values.ingress.tlscrt | quote }}
  tls.key: {{ default "" .Values.ingress.tlskey | quote }}
{{ end }}