# This secret is created to use in htpps openshift route.
{{ if (empty (.Values.openshifttls.enable | quote) | ternary .Values.global.openshiftTls .Values.openshifttls.enable) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name| default .Values.global.csSecrets }}{{ "-tls" }} 
type: kubernetes.io/tls
data:
  tls.crt: {{ default "" .Values.ingress.tlscrt | b64enc | quote }}
  tls.key: {{ default "" .Values.ingress.tlskey | b64enc | quote }}
  ingress.keystorepassword: {{ default "" .Values.ingress.keystorepassword| b64enc | quote }}
{{ end }}