# This secret is used for CS, DB

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name| default .Values.global.csSecrets }}
type: Opaque
data:
  tls.crt: {{ default "" .Values.ingress.tlscrt | b64enc | quote }}
  tls.key: {{ default "" .Values.ingress.tlskey | b64enc | quote }}
  ingress.keystorepassword: {{ default "" .Values.ingress.keystorepassword| b64enc | quote }}
  commontruststorepassword: {{ default "" .Values.commonTruststore.password| b64enc | quote }}
  commontls.crt: {{ default "" .Values.commonTruststore.commontlscrt | b64enc | quote }}
  commontls.key: {{ default "" .Values.commonTruststore.commontlskey | b64enc | quote }}
  rootPassword: {{ default "" .Values.contentserver.install.root.password | b64enc | quote }}
  installOwner: {{ default "" .Values.contentserver.installOwner.userName | default .Values.global.installOwnerUsername | b64enc | quote }}
  installOwnerPassword: {{ required "A valid contentserver.installOwner.password is required!" ( .Values.contentserver.installOwner.password | b64enc | quote )}}
  globalRegistryPassword: {{ required "A valid contentserver.globalRegistry.password is required!" ( .Values.contentserver.globalRegistry.password | b64enc | quote )}}
  aekAlgorithm: {{ default "" .Values.contentserver.aek.algorithm | b64enc | quote }}
  aekPassphrase: {{ required "A valid contentserver.aek.passphrase is required!" ( .Values.contentserver.aek.passphrase | b64enc | quote )}}
  oldaekPassphrase: {{ default "" .Values.contentserver.aek.oldPassphrase | b64enc | quote }}
  kmsApiKey: {{ default "" .Values.kms.apiKey | b64enc | quote }}
  appServerAdminPassword: {{ required "A valid contentserver.install.appserver.admin.password is required!" ( .Values.contentserver.install.appserver.admin.password | b64enc | quote )}}
  dbUserName: {{ default "" .Values.database.userName | b64enc | quote }}
  dbPassword: {{ required "A valid database.password is required!" ( .Values.database.password | b64enc | quote )}}
  dbCertificate: {{ default "" .Values.database.certificate | b64enc }}
  docbasePassword: {{ required "A valid docbase.password is required!" ( .Values.docbase.password | b64enc | quote )}} 
  s3StoreBaseUrl: {{ default "" .Values.s3Store.s3StoreBaseUrl | b64enc | quote }}
  s3StoreCredentialID: {{ default "" .Values.s3Store.s3StoreCredentialID | b64enc | quote }}
  s3StoreCredentialKEY: {{ default "" .Values.s3Store.s3StoreCredentialKEY | b64enc | quote }}
  s3sslCertificate: {{ default "" .Values.s3Store.certificate | b64enc }}
  newrelicLicensekey: {{ default "" .Values.newrelic.license_key | b64enc | quote }}
  dbrCertpassword: {{ default "" .Values.docbroker.certificate.password | b64enc | quote }}
  dbrCertAekPassphrase: {{ default "" .Values.docbroker.certificate.aekpassphrase | b64enc | quote }}
  dbrCertTrustPassword: {{ default "" .Values.docbroker.certificate.trustpassword | b64enc | quote }}
  dbrCertPemCertPrivKey: {{ default "" .Values.docbroker.certificate.pemCertPrivKey | b64enc | quote }}
  dbrCertPemCertificate: {{ default "" .Values.docbroker.certificate.pemCertificate | b64enc | quote }}  
  csCertPassword: {{ default "" .Values.contentserver.certificate.password | b64enc | quote }}
  csCertTrustPassword: {{ default "" .Values.contentserver.certificate.trustpassword | b64enc | quote }}  
  csCertPemCertPrivKey: {{ default "" .Values.contentserver.certificate.pemCertPrivKey | b64enc | quote }}
  csCertPemCertificate: {{ default "" .Values.contentserver.certificate.pemCertificate | b64enc | quote }}
  restStoreBaseUrl: {{ default "" .Values.restStore.restStoreBaseUrl | b64enc | quote }}
  restStoreCredentialID: {{ default "" .Values.restStore.restStoreCredentialID | b64enc | quote }}
  restStoreCredentialKEY: {{ default "" .Values.restStore.restStoreCredentialKEY | b64enc | quote }}
  azureStoresslCertificate: {{ default "" .Values.restStore.azurecertificate | b64enc }}
  gcpStoresslCertificate: {{ default "" .Values.restStore.gcpcertificate | b64enc }}
  gcpStorecredentials: {{ default "" .Values.gcpStore_credentials | b64enc | quote }}
  drServiceAccountUser: {{ default "" .Values.clients.drServiceAccountUser  | b64enc | quote }}
  drServiceAccountPassword: {{ default "" .Values.clients.drServiceAccountPassword  | b64enc | quote }}
  smtpUser: {{ default "" .Values.email.smtpUser | b64enc | quote }}
  smtpPass: {{ default "" .Values.email.smtpPass | b64enc | quote }}
  m365ClientId: {{ default "" .Values.email.m365ClientId | b64enc | quote }}
  m365ClientSecret: {{ default "" .Values.email.m365ClientSecret | b64enc | quote }}
  smtpSSLCertificate: {{ default "" .Values.email.smtpSSLCertificate | b64enc | quote }}
  preferencePassword: {{ default "" .Values.clients.preferencePassword  | b64enc | quote }}
  presetPassword: {{ default "" .Values.clients.presetPassword  | b64enc | quote }}
  zk_password: {{ default "" .Values.documentumsearch.zk_password  | b64enc | quote }}
  solr_zk_password: {{ default "" .Values.documentumsearch.solr_zk_password  | b64enc | quote }}
  solr_auth_password: {{ default "" .Values.documentumsearch.solr_auth_password  | b64enc | quote }}
