{{- if and .Values.enabled .Values.createRole (not .Values.vault.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "otdsws.name" . }}-role
{{- if and .Values.migration.enabled .Values.migration.preUpgradeJob.enabled .Release.IsUpgrade}}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
{{- if .Values.global.namespace }}
    "meta.helm.sh/release-namespace": {{ .Values.global.namespace }}
{{- else }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
{{- end }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "otdsws.name" . }}-rbac
{{- if and .Values.migration.enabled .Values.migration.preUpgradeJob.enabled .Release.IsUpgrade}}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
{{- if .Values.global.namespace }}
    "meta.helm.sh/release-namespace": {{ .Values.global.namespace }}
{{- else }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
{{- end }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "otdsws.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ default .Values.global.serviceAccountName .Values.serviceAccountName }}
---
{{- end }}