{{- if eq .Values.enabled true }}
{{- $customsecretname := default .Values.global.existingSecret .Values.customSecretName -}}
########################################################################
# OpenText Directory Services (OTDS)
########################################################################
{{- if eq .Values.statefulSet true }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
apiVersion: apps/v1
metadata:
  name: {{ template "otdsws.name" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
spec:
{{- if eq .Values.statefulSet true }}
  serviceName: {{ template "otdsws.service" . }}
{{- end }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- include "getExtraPodMatchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vault.agentInjector }}
        vault.hashicorp.com/agent-inject: 'true'
      {{- if .Values.vault.namespace }}
        vault.hashicorp.com/namespace: {{ .Values.vault.namespace }}
      {{- end }}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authpath }}
        vault.hashicorp.com/role: {{ .Values.vault.role }}
        vault.hashicorp.com/agent-cache-enable: 'true'
      {{- if .Values.vault.proxyAddress }}
        vault.hashicorp.com/proxy-address: {{ .Values.vault.proxyAddress }}
      {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "getExtraPodMatchLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
        seccompProfile:
          type: RuntimeDefault
{{- end }}
        runAsNonRoot: true
      {{- if .Values.affinity }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- with .Values.topologySpreadConstraints }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: {{ printf "%s/%s:%s" .image.source .image.name .image.tag }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          command:
          - cp
          - -r
          - /otdsws
          - /opt/config/customfiles
          volumeMounts:
          - name: {{ template "otdsws.name" $ }}-customfiles-volume
            mountPath: /opt/config/customfiles
        {{- end }}
{{- if .Values.otdsdb.automaticDatabaseCreation.enabled }}
        - name: init-otds-db
          image: {{ include "otiv.init.image.path" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          env:
{{- if $customsecretname }}
          - name: SECRET_NAME
            value: {{ $customsecretname }}
{{- end }}
          - name: SERVICE_ID
            value: {{ .Chart.Name }}
          - name: SKIP_OTDS_CHECKS
            value: 'True'
          - name: PITHOS_PROVIDER
            value:  {{ include "otdsdb.url.type" . }}
          - name: PITHOS_HOST
            value:  {{ include "otdsdb.url.host" . }}
          - name: PITHOS_PORT
            value:  {{ include "otdsdb.url.port" . }}
          - name: DB_ADMIN_USER
            value:  {{ .Values.global.database.adminUsername }}
          - name: PITHOS_ADMIN_DB
            value:  {{ .Values.global.database.adminDatabase }}
          - name: DB_ADM_PWD_KEY
            value: {{ .Values.global.dbSecretKey }}
          - name: OTDS_DB_SECRET_NAME
            value: {{ default "otdsws-secrets" $customsecretname }}
          - name: OTDS_DB_PWD_KEY
            value: OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD
          - name: OTDS_DB
            value:  {{ include "otdsdb.url.name" . }}
          - name: OTDS_DB_USER
            valueFrom:
              secretKeyRef:
{{- if $customsecretname }}
                name: {{ $customsecretname }}
{{- else }}
                name: {{ template "otdsws.name" . }}-secrets
{{- end }}
                key: OTDS_JAKARTA_PERSISTENCE_JDBC_USER
          command:
            -  python
            -  ./scripts/otdsDatabase.py
{{- end }}
      volumes:
        - name: {{ template "otdsws.name" . }}-temp-volume
          emptyDir:
            sizeLimit: {{ .Values.emptyDirLimits.tempDir }}
        - name: {{ template "otdsws.name" . }}-logs-volume
          emptyDir:
            sizeLimit: {{ .Values.emptyDirLimits.logsDir }}
        - name: {{ template "otdsws.name" . }}-work-volume
          emptyDir:
            sizeLimit: {{ .Values.emptyDirLimits.workDir }}
{{- if .Values.pvc.enabled }}
        - name: {{ template "otdsws.name" . }}-otds-data-volume
          persistentVolumeClaim:
            claimName: {{ template "otdsws.name" . }}-pvc
{{- end }}
{{- if .Values.vault.enabled }}
        - name: {{ template "otdsws.name" . }}-vault-token
          projected:
            sources:
            - serviceAccountToken:
                path: vault-token
                expirationSeconds: 7200
{{- if .Values.vault.tokenAudience }}
                audience: {{ .Values.vault.tokenAudience }}
{{- end }}
{{- end }}
{{- if and .Values.migration.enabled .Values.migration.usingLegacyImage (not .Values.migration.preUpgradeJob.enabled) }}
        - name: {{ template "otdsws.name" . }}-legacy-image-volume
          persistentVolumeClaim:
            claimName: {{ .Values.migration.legacyImagePVC }}
{{- end }}
{{- if eq .Values.enableBootstrapConfig true }}
        - name: {{ template "otdsws.name" . }}-bootstrap-volume
          secret:
            secretName: {{ template "otdsws.name" . }}-bootstrap
{{- end }}
{{- if eq .Values.kerberos.enabled true }}
        - name: {{ template "otdsws.name" . }}-kerberos-volume
          secret:
            secretName: {{ template "otdsws.name" . }}-kerberos
{{- end }}
{{- if eq .Values.enableCustomizedTruststore true }}
        - name: {{ template "otdsws.name" . }}-certs-volume
          secret:
            secretName: {{ template "otdsws.name" . }}-certs
        - name: {{ template "otdsws.name" . }}-truststore-volume
          emptyDir:
            sizeLimit: {{ .Values.emptyDirLimits.customTrustStoreDir }}
{{- end }}
{{- if .Values.initContainers }}
        - name: {{ template "otdsws.name" . }}-customfiles-volume
          emptyDir:
            sizeLimit: {{ .Values.emptyDirLimits.initContainerDir }}
{{- end }}
      serviceAccountName: {{ default .Values.global.serviceAccountName .Values.serviceAccountName }}
      containers:
      - name: {{ template "otdsws.name" . }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        envFrom:
        - configMapRef:
            name: {{ template "otdsws.name" . }}-configmap
        env:
{{- if (not .Values.vault.enabled) }}
        - name: OTDS_K8S_SECRET_NAME
{{- if $customsecretname }}
          value: {{ $customsecretname }}
{{- else }}
          value: {{ template "otdsws.name" . }}-secrets
{{- end }}
{{- end }}
        volumeMounts:
          - name: {{ template "otdsws.name" . }}-temp-volume
            mountPath: /opt/tomcat/temp
          - name: {{ template "otdsws.name" . }}-logs-volume
            mountPath: /opt/tomcat/logs
          - name: {{ template "otdsws.name" . }}-work-volume
            mountPath: /opt/tomcat/work
{{- if .Values.pvc.enabled }}
          - name: {{ template "otdsws.name" . }}-otds-data-volume
            mountPath: /opt/otdsdata
{{- end }}
{{- if .Values.vault.enabled }}
          - name: {{ template "otdsws.name" . }}-vault-token
            mountPath: /var/run/secrets/tokens
{{- end }}
{{- if and .Values.migration.enabled .Values.migration.usingLegacyImage (not .Values.migration.preUpgradeJob.enabled) }}
          - name: {{ template "otdsws.name" . }}-legacy-image-volume
            mountPath: /opt/otds
{{- end }}
{{- if eq .Values.enableBootstrapConfig true }}
          - name: {{ template "otdsws.name" . }}-bootstrap-volume
            mountPath: /opt/config/bootstrap
{{- end }}
{{- if eq .Values.kerberos.enabled true }}
          - name: {{ template "otdsws.name" . }}-kerberos-volume
            mountPath: /opt/config/kerberos
{{- end }}
{{- if eq .Values.enableCustomizedTruststore true }}
          - name: {{ template "otdsws.name" . }}-certs-volume
            mountPath: /opt/config/certificates
          - name: {{ template "otdsws.name" . }}-truststore-volume
            mountPath: /opt/config/truststore
{{- end }}
{{- if .Values.initContainers }}
          - name: {{ template "otdsws.name" . }}-customfiles-volume
            mountPath: /opt/config/customfiles
{{- end }}
        readinessProbe:
          httpGet:
            path: {{ template "otdsws.path" . }}/health/readiness
            port: {{ .Values.targetPort }}
          periodSeconds: 50
          timeoutSeconds: 5
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: {{ template "otdsws.path" . }}/health/liveness
            port: {{ .Values.targetPort }}
          periodSeconds: 40
          timeoutSeconds: 5
{{- if semverCompare "<1.18-0" .Capabilities.KubeVersion.GitVersion }}
          initialDelaySeconds: 240
{{- end }}
{{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
          initialDelaySeconds: 20
        startupProbe:
          httpGet:
            path: {{ template "otdsws.path" . }}/health/liveness
            port: {{ .Values.targetPort }}
          periodSeconds: 10
          failureThreshold: 24
{{- end }}
        image: {{ include "otds.image" . }}
        imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.image.pullPolicy }}
{{- if (eq (default .Values.global.resourceRequirements .Values.resources.enabled) true) }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
{{- end }}
        ports:
        - containerPort: {{ .Values.targetPort }}
      hostname: {{ .Values.hostname }}
{{- if (default .Values.global.imagePullSecret .Values.image.pullSecret) }}
      imagePullSecrets:
      - name: {{ default .Values.global.imagePullSecret .Values.image.pullSecret }}
{{- end }}
{{- end }}
