# This secret is used for SNC Certificate
{{ if eq .Values.snc.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snc.secret.name }}
data:
  {{ .Values.snc.sap.certificateName }}: {{ default "" .Values.snc.sap.certificate | b64enc | quote }}
{{ end }}