apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.custom.PVCname }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass | default .Values.global.rwmStorage}}
  resources:
    requests:
      storage: {{ .Values.custom.size }}