#Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Values.namespace | default .Release.Namespace}}
  {{- with .Values.service.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default  .Values.global.webappServiceType}}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: https
      port: {{ .Values.containers.records.probing.healthPortHttps }}
      targetPort: 8443
  selector:
    app: {{ .Values.deployment.name }}
