apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ .Values.deployment.name }}-logging-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  log4j2.properties: |-
    name=PropertiesConfig
    property.filename=documentum/logs/{{ .Values.logging.filename }}
    #status=DEBUG
    rootLogger.level={{ .Values.logging.rootLoggerLevel }}
    rootLogger.appenderRefs=A1,F1
    rootLogger.appenderRef.A1.ref=STDOUT
    rootLogger.appenderRef.F1.ref=FILE
    monitorInterval = {{ .Values.logging.monitorInterval }}
    #------------------- CONSOLE --------------------------
    appender.A1.type=Console
    appender.A1.name=STDOUT
    appender.A1.layout.type=PatternLayout
    appender.A1.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.A1.filter.threshold.type=ThresholdFilter
    appender.A1.filter.threshold.level={{ .Values.logging.consoleThresholdLevel }}
    #------------------- FILE --------------------------
    appender.F1.type=RollingFile
    appender.F1.name=FILE
    appender.F1.fileName=${filename}
    appender.F1.filePattern=${filename}.%d{yyyy-MM-dd}-%i.log
    appender.F1.layout.type=PatternLayout
    appender.F1.layout.pattern=%d{ABSOLUTE} %5p [%t] %c - %m%n
    appender.F1.policies.type=Policies
    appender.F1.policies.time.type=TimeBasedTriggeringPolicy
    appender.F1.policies.time.interval=1
    appender.F1.policies.time.modulate=true
    appender.F1.policies.size.type=SizeBasedTriggeringPolicy
    appender.F1.policies.size.size={{ .Values.logging.logFileSize}}
    appender.F1.strategy.type=DefaultRolloverStrategy
    appender.F1.strategy.max={{ .Values.logging.maxLogFiles }}