#DBR PVC CERTIFICATE
{{ if or (eq .Values.certificate.use_certificate true) (eq .Values.global.useCertificate true) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName | default .Values.global.dbrServiceName}}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolume.pvcAccessModes }}
{{ if .Values.persistentVolume.pvcStorageClass }}
  storageClassName: {{ .Values.persistentVolume.pvcStorageClass }}
{{ else }}
  storageClassName: {{ .Values.persistentVolume.storageClass | default .Values.global.rwoStorage }}
{{ end }}
{{ if .Values.persistentVolume.existVolumePv }}
  volumeName: {{ .Values.persistentVolume.existVolumePv }}
{{ end }}
  resources:
    requests:
{{ if .Values.persistentVolume.pvcStorageSize }}
      storage: {{ .Values.persistentVolume.pvcStorageSize }}
{{ else }}
      storage: {{ .Values.persistentVolume.size }}
{{ end }}
{{ end }}