{{ if eq .Values.platform "gcp" }}
{{ if (empty (.Values.ExtDocbroker.enable | quote) | ternary .Values.global.externalAccessEnabled .Values.ExtDocbroker.enable) }}
{{ if eq .Values.ExtDocbroker.createExtService true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName | default .Values.global.dbrServiceName }}        
  name: dbrext-{{ .Values.serviceName | default .Values.global.dbrServiceName }}
{{ if eq .Values.ExtDocbroker.useLBAnnotations true }}
  annotations:
    {{ toJson .Values.ExtDocbroker.LBAnnotations }}
{{ end }}     
spec:    
  ports:
  - name: dbrnative
    port: 80
    protocol: TCP
    targetPort: {{ .Values.ports.extNativePort }}
  - name: dbrssl    
    port: 81
    protocol: TCP
    targetPort: {{ .Values.ports.extSSLPort }}
  selector:
    app: {{ .Values.serviceName | default .Values.global.dbrServiceName }}
  sessionAffinity: None
  type: LoadBalancer
{{ end }}
{{ end }}
{{ end }}
