#Docbroker Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default .Values.global.dbrServiceName }}
  labels:
    app: {{ .Values.serviceName | default .Values.global.dbrServiceName }}
spec:
  ports:
  - port: {{ .Values.ports.docbrokerPort }}
    name: docbrokerport
  - port: {{ .Values.ports.docbrokrSSLport }}
    name: docbrokrsslport
  - port: {{ .Values.ports.extNativePort }}
    name: extdocbrokerport
  - port: {{ .Values.ports.extSSLPort }}
    name: extdocbrokrsslport
  clusterIP: None
  selector:
    app: {{ .Values.serviceName | default .Values.global.dbrServiceName }}
