kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.pvcName }}
spec:
  accessModes:
    -  {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default .Values.global.rwmStorage}}
  {{ if .Values.persistence.existVolumePv }}
  volumeName: {{ .Values.persistence.existVolumePv }}
  {{ end }}
