{{- if .Values.serviceAccount.createserviceaccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.serviceAccountName | default .Values.global.documentumserviceaccount}}
  namespace: {{ .Release.Namespace }}
{{- end }}