kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceName }}-read-pods
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.serviceAccountName | default .Values.global.documentumserviceaccount }}
roleRef:
  kind: Role 
  name: {{ .Values.serviceName }}-pod-reader 
  apiGroup: rbac.authorization.k8s.io