#Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
{{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.webappServiceType | default .Values.global.webappServiceType }}
  sessionAffinity: ClientIP
  ports:
  - name: dfs-http-port
    port: {{ .Values.service.ports.httpPort }}
    targetPort: dfs-http-port
  - name: dfs-secure-port
    port: {{ .Values.service.ports.sslPort }}
    targetPort: dfs-secure-port
  selector:
    app: {{ .Values.serviceName }}
