#IJMS PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolume.pvcAccessModes }}
  storageClassName: {{ .Values.persistentVolume.storageClass | default .Values.global.rwmStorage }}
{{ if .Values.persistentVolume.existVolumePv }}
  volumeName: {{ .Values.persistentVolume.existVolumePv }}
{{ end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}